### ISSUE TITLE
INFRA-001: AWS Cloud Infrastructure Architecture

### ISSUE THREAD

**Issue by sean-rowe** [sean-rowe/pediatric-therapy-resource#55]
## Story
As a platform engineer, I want a scalable, secure, and highly available cloud infrastructure on AWS, so that the pediatric therapy platform can handle varying loads, maintain 99.9% uptime, and ensure data security and compliance with healthcare regulations.

## Acceptance Criteria
- Multi-region deployment for disaster recovery
- Auto-scaling application and database tiers
- Container orchestration with Kubernetes (EKS)
- Infrastructure as Code (Terraform/CloudFormation)
- Comprehensive monitoring and alerting
- Automated backup and recovery systems
- Security compliance (HIPAA, SOC 2)
- CI/CD pipeline integration
- Cost optimization and resource management

### Infrastructure Architecture
```yaml
# Infrastructure as Code - Terraform Configuration
# Main infrastructure components

# VPC and Networking
resource "aws_vpc" "main" {
  cidr_block           = "10.0.0.0/16"
  enable_dns_hostnames = true
  enable_dns_support   = true

  tags = {
    Name        = "pediatric-therapy-vpc"
    Environment = var.environment
    Project     = "pediatric-therapy"
  }
}

# Public Subnets (for ALB, NAT Gateway)
resource "aws_subnet" "public" {
  count             = length(var.availability_zones)
  vpc_id            = aws_vpc.main.id
  cidr_block        = "10.0.${count.index + 1}.0/24"
  availability_zone = var.availability_zones[count.index]

  map_public_ip_on_launch = true

  tags = {
    Name = "public-subnet-${count.index + 1}"
    Type = "Public"
  }
}

# Private Subnets (for EKS, RDS)
resource "aws_subnet" "private" {
  count             = length(var.availability_zones)
  vpc_id            = aws_vpc.main.id
  cidr_block        = "10.0.${count.index + 10}.0/24"
  availability_zone = var.availability_zones[count.index]

  tags = {
    Name                              = "private-subnet-${count.index + 1}"
    Type                              = "Private"
    "kubernetes.io/role/internal-elb" = "1"
    "kubernetes.io/cluster/${var.cluster_name}" = "owned"
  }
}

# Database Subnets
resource "aws_subnet" "database" {
  count             = length(var.availability_zones)
  vpc_id            = aws_vpc.main.id
  cidr_block        = "10.0.${count.index + 20}.0/24"
  availability_zone = var.availability_zones[count.index]

  tags = {
    Name = "database-subnet-${count.index + 1}"
    Type = "Database"
  }
}

# Internet Gateway
resource "aws_internet_gateway" "main" {
  vpc_id = aws_vpc.main.id

  tags = {
    Name = "main-igw"
  }
}

# NAT Gateways
resource "aws_eip" "nat" {
  count  = length(var.availability_zones)
  domain = "vpc"

  tags = {
    Name = "nat-eip-${count.index + 1}"
  }
}

resource "aws_nat_gateway" "main" {
  count         = length(var.availability_zones)
  allocation_id = aws_eip.nat[count.index].id
  subnet_id     = aws_subnet.public[count.index].id

  tags = {
    Name = "nat-gateway-${count.index + 1}"
  }

  depends_on = [aws_internet_gateway.main]
}

# EKS Cluster
resource "aws_eks_cluster" "main" {
  name     = var.cluster_name
  role_arn = aws_iam_role.eks_cluster.arn
  version  = "1.28"

  vpc_config {
    subnet_ids              = concat(aws_subnet.private[*].id, aws_subnet.public[*].id)
    endpoint_private_access = true
    endpoint_public_access  = true
    public_access_cidrs     = ["0.0.0.0/0"]
  }

  encryption_config {
    provider {
      key_arn = aws_kms_key.eks.arn
    }
    resources = ["secrets"]
  }

  enabled_cluster_log_types = [
    "api",
    "audit",
    "authenticator",
    "controllerManager",
    "scheduler"
  ]

  depends_on = [
    aws_iam_role_policy_attachment.eks_cluster_policy,
    aws_iam_role_policy_attachment.eks_service_policy,
  ]

  tags = {
    Name = var.cluster_name
  }
}

# EKS Node Groups
resource "aws_eks_node_group" "main" {
  cluster_name    = aws_eks_cluster.main.name
  node_group_name = "main-node-group"
  node_role_arn   = aws_iam_role.eks_node_group.arn
  subnet_ids      = aws_subnet.private[*].id

  capacity_type  = "ON_DEMAND"
  instance_types = ["t3.large", "t3.xlarge"]

  scaling_config {
    desired_size = 3
    max_size     = 10
    min_size     = 2
  }

  update_config {
    max_unavailable_percentage = 25
  }

  # Kubernetes labels
  labels = {
    "nodegroup-name" = "main-node-group"
    "nodegroup-type" = "OnDemand"
  }

  # Taints for specialized workloads
  taint {
    key    = "dedicated"
    value  = "therapy-workloads"
    effect = "NO_SCHEDULE"
  }

  depends_on = [
    aws_iam_role_policy_attachment.eks_worker_node_policy,
    aws_iam_role_policy_attachment.eks_cni_policy,
    aws_iam_role_policy_attachment.eks_container_registry_policy,
  ]

  tags = {
    Name = "main-node-group"
  }
}

# Spot Instance Node Group for batch processing
resource "aws_eks_node_group" "spot" {
  cluster_name    = aws_eks_cluster.main.name
  node_group_name = "spot-node-group"
  node_role_arn   = aws_iam_role.eks_node_group.arn
  subnet_ids      = aws_subnet.private[*].id

  capacity_type  = "SPOT"
  instance_types = ["t3.large", "t3.xlarge", "m5.large", "m5.xlarge"]

  scaling_config {
    desired_size = 2
    max_size     = 20
    min_size     = 0
  }

  labels = {
    "nodegroup-name" = "spot-node-group"
    "nodegroup-type" = "Spot"
  }

  taint {
    key    = "spot-instance"
    value  = "true"
    effect = "NO_SCHEDULE"
  }

  tags = {
    Name = "spot-node-group"
  }
}

# RDS Database Cluster (Aurora PostgreSQL)
resource "aws_rds_cluster" "main" {
  cluster_identifier      = "pediatric-therapy-cluster"
  engine                  = "aurora-postgresql"
  engine_version          = "15.3"
  availability_zones      = var.availability_zones
  database_name           = "therapy_platform"
  master_username         = var.db_username
  master_password         = var.db_password
  backup_retention_period = 30
  preferred_backup_window = "03:00-04:00"
  preferred_maintenance_window = "sun:04:00-sun:05:00"
  
  vpc_security_group_ids = [aws_security_group.rds.id]
  db_subnet_group_name   = aws_db_subnet_group.main.name
  
  storage_encrypted   = true
  kms_key_id         = aws_kms_key.rds.arn
  
  enabled_cloudwatch_logs_exports = ["postgresql"]
  
  deletion_protection = true
  skip_final_snapshot = false
  final_snapshot_identifier = "pediatric-therapy-final-snapshot"

  tags = {
    Name = "pediatric-therapy-cluster"
  }
}

# RDS Cluster Instances
resource "aws_rds_cluster_instance" "cluster_instances" {
  count              = 2
  identifier         = "aurora-instance-${count.index}"
  cluster_identifier = aws_rds_cluster.main.id
  instance_class     = "db.r6g.large"
  engine             = aws_rds_cluster.main.engine
  engine_version     = aws_rds_cluster.main.engine_version

  performance_insights_enabled = true
  monitoring_interval          = 60
  monitoring_role_arn          = aws_iam_role.rds_enhanced_monitoring.arn

  tags = {
    Name = "aurora-instance-${count.index}"
  }
}

# Read Replica for reporting
resource "aws_rds_cluster_instance" "read_replica" {
  identifier         = "aurora-read-replica"
  cluster_identifier = aws_rds_cluster.main.id
  instance_class     = "db.r6g.large"
  engine             = aws_rds_cluster.main.engine
  engine_version     = aws_rds_cluster.main.engine_version

  performance_insights_enabled = true
  
  tags = {
    Name = "aurora-read-replica"
    Role = "ReadReplica"
  }
}

# ElastiCache Redis Cluster
resource "aws_elasticache_replication_group" "main" {
  replication_group_id       = "therapy-redis"
  description                = "Redis cluster for session storage and caching"
  
  node_type                  = "cache.r6g.large"
  port                       = 6379
  parameter_group_name       = aws_elasticache_parameter_group.redis.name
  
  num_cache_clusters         = 3
  automatic_failover_enabled = true
  multi_az_enabled          = true
  
  subnet_group_name = aws_elasticache_subnet_group.main.name
  security_group_ids = [aws_security_group.redis.id]
  
  at_rest_encryption_enabled = true
  transit_encryption_enabled = true
  auth_token                 = var.redis_auth_token
  
  log_delivery_configuration {
    destination      = aws_cloudwatch_log_group.redis.name
    destination_type = "cloudwatch-logs"
    log_format       = "text"
    log_type         = "slow-log"
  }

  tags = {
    Name = "therapy-redis"
  }
}

# S3 Buckets for different purposes
resource "aws_s3_bucket" "therapy_resources" {
  bucket = "pediatric-therapy-resources-${var.environment}"

  tags = {
    Name        = "therapy-resources"
    Environment = var.environment
    Purpose     = "TherapyResources"
  }
}

resource "aws_s3_bucket" "patient_data" {
  bucket = "pediatric-therapy-patient-data-${var.environment}"

  tags = {
    Name        = "patient-data"
    Environment = var.environment
    Purpose     = "PatientData"
    Compliance  = "HIPAA"
  }
}

resource "aws_s3_bucket" "backups" {
  bucket = "pediatric-therapy-backups-${var.environment}"

  tags = {
    Name        = "backups"
    Environment = var.environment
    Purpose     = "Backups"
  }
}

# S3 Bucket Configurations
resource "aws_s3_bucket_encryption" "therapy_resources" {
  bucket = aws_s3_bucket.therapy_resources.id

  server_side_encryption_configuration {
    rule {
      apply_server_side_encryption_by_default {
        kms_master_key_id = aws_kms_key.s3.arn
        sse_algorithm     = "aws:kms"
      }
    }
  }
}

resource "aws_s3_bucket_versioning" "therapy_resources" {
  bucket = aws_s3_bucket.therapy_resources.id
  versioning_configuration {
    status = "Enabled"
  }
}

# CloudFront Distribution
resource "aws_cloudfront_distribution" "main" {
  origin {
    domain_name = aws_s3_bucket.therapy_resources.bucket_regional_domain_name
    origin_id   = "S3-${aws_s3_bucket.therapy_resources.id}"

    s3_origin_config {
      origin_access_identity = aws_cloudfront_origin_access_identity.main.cloudfront_access_identity_path
    }
  }

  enabled             = true
  is_ipv6_enabled     = true
  comment             = "Therapy Resources CDN"
  default_root_object = "index.html"

  default_cache_behavior {
    allowed_methods  = ["DELETE", "GET", "HEAD", "OPTIONS", "PATCH", "POST", "PUT"]
    cached_methods   = ["GET", "HEAD"]
    target_origin_id = "S3-${aws_s3_bucket.therapy_resources.id}"

    forwarded_values {
      query_string = false
      cookies {
        forward = "none"
      }
    }

    viewer_protocol_policy = "redirect-to-https"
    min_ttl                = 0
    default_ttl            = 3600
    max_ttl                = 86400
  }

  restrictions {
    geo_restriction {
      restriction_type = "whitelist"
      locations        = ["US", "CA"]
    }
  }

  viewer_certificate {
    cloudfront_default_certificate = true
  }

  tags = {
    Name = "therapy-resources-cdn"
  }
}

# Application Load Balancer
resource "aws_lb" "main" {
  name               = "therapy-platform-alb"
  internal           = false
  load_balancer_type = "application"
  security_groups    = [aws_security_group.alb.id]
  subnets            = aws_subnet.public[*].id

  enable_deletion_protection = true

  access_logs {
    bucket  = aws_s3_bucket.alb_logs.bucket
    prefix  = "alb-logs"
    enabled = true
  }

  tags = {
    Name = "therapy-platform-alb"
  }
}

# Auto Scaling Groups for different services
resource "aws_autoscaling_group" "api_servers" {
  name                = "api-servers-asg"
  vpc_zone_identifier = aws_subnet.private[*].id
  target_group_arns   = [aws_lb_target_group.api.arn]
  health_check_type   = "ELB"
  health_check_grace_period = 300

  min_size         = 2
  max_size         = 10
  desired_capacity = 3

  launch_template {
    id      = aws_launch_template.api_server.id
    version = "$Latest"
  }

  enabled_metrics = [
    "GroupMinSize",
    "GroupMaxSize",
    "GroupDesiredCapacity",
    "GroupInServiceInstances",
    "GroupTotalInstances"
  ]

  tag {
    key                 = "Name"
    value               = "api-server"
    propagate_at_launch = true
  }
}

# Launch Template for API Servers
resource "aws_launch_template" "api_server" {
  name_prefix   = "api-server-"
  image_id      = data.aws_ami.amazon_linux.id
  instance_type = "t3.medium"
  key_name      = var.key_pair_name

  vpc_security_group_ids = [aws_security_group.api_server.id]

  iam_instance_profile {
    name = aws_iam_instance_profile.api_server.name
  }

  user_data = base64encode(templatefile("${path.module}/user_data/api_server.sh", {
    environment = var.environment
  }))

  tag_specifications {
    resource_type = "instance"
    tags = {
      Name = "api-server"
      Type = "APIServer"
    }
  }
}

# KMS Keys for encryption
resource "aws_kms_key" "main" {
  description             = "Main KMS key for pediatric therapy platform"
  deletion_window_in_days = 7

  tags = {
    Name = "pediatric-therapy-main-key"
  }
}

resource "aws_kms_key" "rds" {
  description             = "KMS key for RDS encryption"
  deletion_window_in_days = 7

  tags = {
    Name = "pediatric-therapy-rds-key"
  }
}

resource "aws_kms_key" "s3" {
  description             = "KMS key for S3 encryption"
  deletion_window_in_days = 7

  tags = {
    Name = "pediatric-therapy-s3-key"
  }
}

# CloudWatch Log Groups
resource "aws_cloudwatch_log_group" "eks" {
  name              = "/aws/eks/${var.cluster_name}/cluster"
  retention_in_days = 30

  tags = {
    Name = "eks-cluster-logs"
  }
}

resource "aws_cloudwatch_log_group" "application" {
  name              = "/therapy-platform/application"
  retention_in_days = 90

  tags = {
    Name = "application-logs"
  }
}

# CloudWatch Alarms
resource "aws_cloudwatch_metric_alarm" "high_cpu" {
  alarm_name          = "high-cpu-utilization"
  comparison_operator = "GreaterThanThreshold"
  evaluation_periods  = "2"
  metric_name         = "CPUUtilization"
  namespace           = "AWS/EKS"
  period              = "300"
  statistic           = "Average"
  threshold           = "80"
  alarm_description   = "This metric monitors eks cpu utilization"
  alarm_actions       = [aws_sns_topic.alerts.arn]

  dimensions = {
    ClusterName = aws_eks_cluster.main.name
  }
}

# SNS Topic for alerts
resource "aws_sns_topic" "alerts" {
  name = "therapy-platform-alerts"

  tags = {
    Name = "therapy-platform-alerts"
  }
}

# Route53 Hosted Zone
resource "aws_route53_zone" "main" {
  name = var.domain_name

  tags = {
    Name = "therapy-platform-zone"
  }
}

# ACM Certificate
resource "aws_acm_certificate" "main" {
  domain_name       = var.domain_name
  validation_method = "DNS"

  subject_alternative_names = [
    "*.${var.domain_name}"
  ]

  lifecycle {
    create_before_destroy = true
  }

  tags = {
    Name = "therapy-platform-cert"
  }
}

# WAF Web ACL
resource "aws_wafv2_web_acl" "main" {
  name  = "therapy-platform-waf"
  scope = "CLOUDFRONT"

  default_action {
    allow {}
  }

  rule {
    name     = "RateLimitRule"
    priority = 1

    override_action {
      none {}
    }

    statement {
      rate_based_statement {
        limit              = 2000
        aggregate_key_type = "IP"
      }
    }

    visibility_config {
      cloudwatch_metrics_enabled = true
      metric_name                = "RateLimitRule"
      sampled_requests_enabled   = true
    }
  }

  rule {
    name     = "AWSManagedRulesCommonRuleSet"
    priority = 2

    override_action {
      none {}
    }

    statement {
      managed_rule_group_statement {
        name        = "AWSManagedRulesCommonRuleSet"
        vendor_name = "AWS"
      }
    }

    visibility_config {
      cloudwatch_metrics_enabled = true
      metric_name                = "CommonRuleSetMetric"
      sampled_requests_enabled   = true
    }
  }

  tags = {
    Name = "therapy-platform-waf"
  }

  visibility_config {
    cloudwatch_metrics_enabled = true
    metric_name                = "therapyPlatformWAF"
    sampled_requests_enabled   = true
  }
}
```

### Kubernetes Manifests
```yaml
# Namespace for therapy platform
apiVersion: v1
kind: Namespace
metadata:
  name: therapy-platform
  labels:
    name: therapy-platform
    compliance: hipaa

---
# ConfigMap for application configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: therapy-platform
data:
  DATABASE_HOST: "therapy-cluster.cluster-abc123.us-west-2.rds.amazonaws.com"
  REDIS_HOST: "therapy-redis.abc123.cache.amazonaws.com"
  S3_BUCKET: "pediatric-therapy-resources-prod"
  LOG_LEVEL: "INFO"
  ENVIRONMENT: "production"

---
# Secret for database credentials
apiVersion: v1
kind: Secret
metadata:
  name: db-credentials
  namespace: therapy-platform
type: Opaque
data:
  username: <base64-encoded-username>
  password: <base64-encoded-password>

---
# Deployment for API service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: therapy-api
  namespace: therapy-platform
  labels:
    app: therapy-api
spec:
  replicas: 3
  selector:
    matchLabels:
      app: therapy-api
  template:
    metadata:
      labels:
        app: therapy-api
    spec:
      serviceAccountName: therapy-api-sa
      containers:
      - name: therapy-api
        image: pediatric-therapy/api:latest
        ports:
        - containerPort: 8080
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: connection-string
        - name: REDIS_URL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: REDIS_HOST
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /ready
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
        securityContext:
          runAsNonRoot: true
          runAsUser: 10001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true

---
# Service for API
apiVersion: v1
kind: Service
metadata:
  name: therapy-api-service
  namespace: therapy-platform
spec:
  selector:
    app: therapy-api
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
  type: ClusterIP

---
# HorizontalPodAutoscaler for API
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: therapy-api-hpa
  namespace: therapy-platform
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: therapy-api
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80

---
# Ingress for API
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: therapy-api-ingress
  namespace: therapy-platform
  annotations:
    kubernetes.io/ingress.class: alb
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/target-type: ip
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-west-2:123456789:certificate/abc123
spec:
  rules:
  - host: api.therapy-platform.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: therapy-api-service
            port:
              number: 80

---
# ServiceAccount with IAM role
apiVersion: v1
kind: ServiceAccount
metadata:
  name: therapy-api-sa
  namespace: therapy-platform
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::123456789:role/TherapyAPIRole

---
# NetworkPolicy for security
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: therapy-api-netpol
  namespace: therapy-platform
spec:
  podSelector:
    matchLabels:
      app: therapy-api
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: ingress-nginx
    ports:
    - protocol: TCP
      port: 8080
  egress:
  - to: []
    ports:
    - protocol: TCP
      port: 5432  # PostgreSQL
    - protocol: TCP
      port: 6379  # Redis
    - protocol: TCP
      port: 443   # HTTPS
```

### Monitoring and Alerting Stack
```yaml
# Prometheus for metrics collection
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        ports:
        - containerPort: 9090
        volumeMounts:
        - name: prometheus-config
          mountPath: /etc/prometheus
        - name: prometheus-storage
          mountPath: /prometheus
        resources:
          requests:
            memory: "1Gi"
            cpu: "500m"
          limits:
            memory: "2Gi"
            cpu: "1000m"
      volumes:
      - name: prometheus-config
        configMap:
          name: prometheus-config
      - name: prometheus-storage
        persistentVolumeClaim:
          claimName: prometheus-pvc

---
# Grafana for visualization
apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana/grafana:latest
        ports:
        - containerPort: 3000
        env:
        - name: GF_SECURITY_ADMIN_PASSWORD
          valueFrom:
            secretKeyRef:
              name: grafana-secret
              key: admin-password
        volumeMounts:
        - name: grafana-storage
          mountPath: /var/lib/grafana
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      volumes:
      - name: grafana-storage
        persistentVolumeClaim:
          claimName: grafana-pvc

---
# AlertManager for alert handling
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
      - name: alertmanager
        image: prom/alertmanager:latest
        ports:
        - containerPort: 9093
        volumeMounts:
        - name: alertmanager-config
          mountPath: /etc/alertmanager
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
      volumes:
      - name: alertmanager-config
        configMap:
          name: alertmanager-config
```

### Backup and Disaster Recovery
```bash
#\!/bin/bash
# Automated backup script

# Database backup
aws rds create-db-cluster-snapshot \
  --db-cluster-identifier therapy-cluster \
  --db-cluster-snapshot-identifier "therapy-cluster-$(date +%Y%m%d-%H%M%S)"

# S3 backup to different region
aws s3 sync s3://pediatric-therapy-resources-prod \
  s3://pediatric-therapy-backup-us-east-1 \
  --storage-class GLACIER_INSTANT_RETRIEVAL

# EKS configuration backup
kubectl get all --all-namespaces -o yaml > k8s-backup-$(date +%Y%m%d).yaml
aws s3 cp k8s-backup-$(date +%Y%m%d).yaml s3://pediatric-therapy-backups-prod/k8s/

# Terraform state backup
terraform state pull > terraform-state-$(date +%Y%m%d).json
aws s3 cp terraform-state-$(date +%Y%m%d).json s3://pediatric-therapy-backups-prod/terraform/
```

### Security Hardening
```yaml
# Pod Security Policy
apiVersion: policy/v1beta1
kind: PodSecurityPolicy
metadata:
  name: therapy-platform-psp
spec:
  privileged: false
  allowPrivilegeEscalation: false
  requiredDropCapabilities:
    - ALL
  volumes:
    - 'configMap'
    - 'emptyDir'
    - 'projected'
    - 'secret'
    - 'downwardAPI'
    - 'persistentVolumeClaim'
  runAsUser:
    rule: 'MustRunAsNonRoot'
  seLinux:
    rule: 'RunAsAny'
  fsGroup:
    rule: 'RunAsAny'

---
# Network Security Group Rules
resource "aws_security_group_rule" "database_access" {
  type                     = "ingress"
  from_port                = 5432
  to_port                  = 5432
  protocol                 = "tcp"
  source_security_group_id = aws_security_group.eks_nodes.id
  security_group_id        = aws_security_group.rds.id
}

# WAF Rules for API protection
resource "aws_wafv2_rule_group" "api_protection" {
  name     = "api-protection-rules"
  scope    = "REGIONAL"
  capacity = 100

  rule {
    name     = "SQLInjectionRule"
    priority = 1

    action {
      block {}
    }

    statement {
      sqli_match_statement {
        field_to_match {
          body {}
        }
        text_transformation {
          priority = 0
          type     = "URL_DECODE"
        }
      }
    }

    visibility_config {
      cloudwatch_metrics_enabled = true
      metric_name                = "SQLInjectionRule"
      sampled_requests_enabled   = true
    }
  }
}
```

### Cost Optimization
```yaml
# Cluster Autoscaler for cost optimization
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cluster-autoscaler
  namespace: kube-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cluster-autoscaler
  template:
    metadata:
      labels:
        app: cluster-autoscaler
    spec:
      containers:
      - image: k8s.gcr.io/autoscaling/cluster-autoscaler:v1.21.0
        name: cluster-autoscaler
        resources:
          limits:
            cpu: 100m
            memory: 300Mi
          requests:
            cpu: 100m
            memory: 300Mi
        command:
        - ./cluster-autoscaler
        - --v=4
        - --stderrthreshold=info
        - --cloud-provider=aws
        - --skip-nodes-with-local-storage=false
        - --expander=least-waste
        - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/therapy-cluster
        - --balance-similar-node-groups
        - --skip-nodes-with-system-pods=false
        env:
        - name: AWS_REGION
          value: us-west-2
```

### Performance Requirements
- Infrastructure provisioning: < 15 minutes via Terraform
- Application deployment: < 5 minutes via Kubernetes
- Auto-scaling response: < 2 minutes
- Database failover: < 30 seconds
- CDN cache hit ratio: > 95%
- SSL termination: < 100ms overhead
- Container startup time: < 30 seconds

### Security Requirements
- All data encrypted at rest and in transit
- HIPAA compliance with audit logging
- Network segmentation with security groups
- Container security scanning
- Secrets management with AWS Secrets Manager
- Regular security patching automation
- Intrusion detection and prevention
- Multi-factor authentication for infrastructure access
EOF < /dev/null
