### ISSUE TITLE
TEST-001: Comprehensive Automated Testing Framework

### ISSUE THREAD

**Issue by sean-rowe** [sean-rowe/pediatric-therapy-resource#56]
## Story
As a software quality engineer, I want comprehensive automated testing frameworks covering unit, integration, end-to-end, performance, and security testing, so that the pediatric therapy platform maintains high reliability, security, and performance standards throughout the development lifecycle.

## Acceptance Criteria
- Automated unit testing with >90% code coverage
- Integration testing for all external APIs and services
- End-to-end testing for critical user journeys
- Performance testing for load and stress scenarios
- Security testing including penetration testing
- Accessibility testing for WCAG compliance
- Mobile responsiveness testing across devices
- Continuous testing in CI/CD pipeline

### Test Framework Architecture
```typescript
// Jest configuration for unit testing
module.exports = {
  preset: 'ts-jest',
  testEnvironment: 'node',
  roots: ['<rootDir>/src'],
  testMatch: [
    '**/__tests__/**/*.ts',
    '**/?(*.)+(spec < /dev/null | test).ts'
  ],
  transform: {
    '^.+\\.ts$': 'ts-jest',
  },
  collectCoverageFrom: [
    'src/**/*.ts',
    '\!src/**/*.d.ts',
    '\!src/**/*.interface.ts',
    '\!src/migrations/**',
  ],
  coverageDirectory: 'coverage',
  coverageReporters: [
    'text',
    'lcov',
    'html',
    'json-summary'
  ],
  coverageThreshold: {
    global: {
      branches: 90,
      functions: 90,
      lines: 90,
      statements: 90
    }
  },
  setupFilesAfterEnv: ['<rootDir>/src/test/setup.ts'],
  testTimeout: 30000,
  moduleNameMapping: {
    '^@/(.*)$': '<rootDir>/src/$1'
  }
};

// Test database setup
import { DataSource } from 'typeorm';
import { PostgreSqlContainer } from '@testcontainers/postgresql';

export class TestDatabase {
  private static container: PostgreSqlContainer;
  private static dataSource: DataSource;

  static async setupTestDatabase(): Promise<DataSource> {
    this.container = new PostgreSqlContainer('postgres:15')
      .withDatabase('therapy_test')
      .withUsername('test_user')
      .withPassword('test_password')
      .withExposedPorts(5432);

    await this.container.start();

    this.dataSource = new DataSource({
      type: 'postgres',
      host: this.container.getHost(),
      port: this.container.getMappedPort(5432),
      username: 'test_user',
      password: 'test_password',
      database: 'therapy_test',
      entities: ['src/entities/**/*.ts'],
      migrations: ['src/migrations/**/*.ts'],
      synchronize: true,
      logging: false,
    });

    await this.dataSource.initialize();
    return this.dataSource;
  }

  static async teardownTestDatabase(): Promise<void> {
    if (this.dataSource) {
      await this.dataSource.destroy();
    }
    if (this.container) {
      await this.container.stop();
    }
  }

  static getDataSource(): DataSource {
    return this.dataSource;
  }
}

// Unit test example for therapy service
describe('TherapySessionService', () => {
  let service: TherapySessionService;
  let repository: Repository<TherapySession>;
  let dataSource: DataSource;

  beforeAll(async () => {
    dataSource = await TestDatabase.setupTestDatabase();
    repository = dataSource.getRepository(TherapySession);
    service = new TherapySessionService(repository);
  });

  afterAll(async () => {
    await TestDatabase.teardownTestDatabase();
  });

  beforeEach(async () => {
    await repository.clear();
  });

  describe('createSession', () => {
    it('should create a therapy session successfully', async () => {
      // Arrange
      const sessionData = {
        patientId: 'patient-123',
        therapistId: 'therapist-456',
        sessionType: 'OT',
        scheduledStart: new Date('2024-01-15T09:00:00Z'),
        duration: 60,
        goals: ['improve fine motor skills']
      };

      // Act
      const result = await service.createSession(sessionData);

      // Assert
      expect(result).toBeDefined();
      expect(result.id).toBeDefined();
      expect(result.patientId).toBe(sessionData.patientId);
      expect(result.therapistId).toBe(sessionData.therapistId);
      expect(result.status).toBe('scheduled');
    });

    it('should throw error for invalid patient ID', async () => {
      // Arrange
      const invalidSessionData = {
        patientId: 'invalid-patient',
        therapistId: 'therapist-456',
        sessionType: 'OT',
        scheduledStart: new Date(),
        duration: 60
      };

      // Act & Assert
      await expect(service.createSession(invalidSessionData))
        .rejects
        .toThrow('Patient not found');
    });

    it('should validate therapist availability', async () => {
      // Arrange
      const conflictingTime = new Date('2024-01-15T09:00:00Z');
      
      // Create existing session
      await service.createSession({
        patientId: 'patient-123',
        therapistId: 'therapist-456',
        sessionType: 'OT',
        scheduledStart: conflictingTime,
        duration: 60
      });

      // Act & Assert
      await expect(service.createSession({
        patientId: 'patient-789',
        therapistId: 'therapist-456',
        sessionType: 'PT',
        scheduledStart: new Date(conflictingTime.getTime() + 30 * 60000), // 30 min later
        duration: 60
      })).rejects.toThrow('Therapist not available');
    });
  });

  describe('updateSessionNotes', () => {
    it('should update session notes and maintain audit trail', async () => {
      // Arrange
      const session = await service.createSession({
        patientId: 'patient-123',
        therapistId: 'therapist-456',
        sessionType: 'OT',
        scheduledStart: new Date(),
        duration: 60
      });

      const notes = {
        sessionSummary: 'Patient showed improvement in grip strength',
        goalsAddressed: ['improve pincer grasp'],
        interventions: ['threading activities', 'play dough exercises'],
        progressNotes: 'Significant improvement noted',
        nextSteps: ['continue current interventions'],
        attachments: []
      };

      // Act
      const updatedSession = await service.updateSessionNotes(session.id, notes);

      // Assert
      expect(updatedSession.notes).toEqual(notes);
      expect(updatedSession.lastModified).toBeDefined();
      expect(updatedSession.modifiedBy).toBe('therapist-456');
    });
  });
});

// Integration test example for API endpoints
describe('Patient API Integration Tests', () => {
  let app: Express;
  let dataSource: DataSource;

  beforeAll(async () => {
    dataSource = await TestDatabase.setupTestDatabase();
    app = createTestApp(dataSource);
  });

  afterAll(async () => {
    await TestDatabase.teardownTestDatabase();
  });

  describe('POST /api/patients', () => {
    it('should create a new patient with valid data', async () => {
      // Arrange
      const patientData = {
        firstName: 'John',
        lastName: 'Doe',
        dateOfBirth: '2018-05-15',
        diagnoses: ['Autism Spectrum Disorder'],
        guardianContact: {
          name: 'Jane Doe',
          email: 'jane.doe@example.com',
          phone: '+1-555-123-4567'
        }
      };

      // Act
      const response = await request(app)
        .post('/api/patients')
        .send(patientData)
        .set('Authorization', 'Bearer valid-jwt-token');

      // Assert
      expect(response.status).toBe(201);
      expect(response.body.firstName).toBe(patientData.firstName);
      expect(response.body.id).toBeDefined();
      expect(response.body.createdAt).toBeDefined();
    });

    it('should validate required fields', async () => {
      // Arrange
      const incompleteData = {
        firstName: 'John'
        // Missing required fields
      };

      // Act
      const response = await request(app)
        .post('/api/patients')
        .send(incompleteData)
        .set('Authorization', 'Bearer valid-jwt-token');

      // Assert
      expect(response.status).toBe(400);
      expect(response.body.errors).toContain('lastName is required');
      expect(response.body.errors).toContain('dateOfBirth is required');
    });

    it('should enforce HIPAA compliance for patient data', async () => {
      // Arrange
      const patientData = {
        firstName: 'John',
        lastName: 'Doe',
        dateOfBirth: '2018-05-15',
        ssn: '123-45-6789' // Sensitive data
      };

      // Act
      const response = await request(app)
        .post('/api/patients')
        .send(patientData)
        .set('Authorization', 'Bearer valid-jwt-token');

      // Assert
      expect(response.status).toBe(201);
      expect(response.body.ssn).toBeUndefined(); // Should not return SSN
      
      // Verify data is encrypted in database
      const patient = await dataSource
        .getRepository(Patient)
        .findOne({ where: { id: response.body.id } });
      
      expect(patient.ssn).not.toBe('123-45-6789'); // Should be encrypted
    });
  });

  describe('GET /api/patients/:id/sessions', () => {
    it('should return paginated session history', async () => {
      // Arrange - Create patient and sessions
      const patient = await createTestPatient();
      await createTestSessions(patient.id, 25); // Create 25 sessions

      // Act
      const response = await request(app)
        .get(`/api/patients/${patient.id}/sessions?page=1&limit=10`)
        .set('Authorization', 'Bearer valid-jwt-token');

      // Assert
      expect(response.status).toBe(200);
      expect(response.body.sessions).toHaveLength(10);
      expect(response.body.pagination.total).toBe(25);
      expect(response.body.pagination.page).toBe(1);
      expect(response.body.pagination.pages).toBe(3);
    });
  });
});
```

### End-to-End Testing with Playwright
```typescript
// E2E test configuration
import { PlaywrightTestConfig } from '@playwright/test';

const config: PlaywrightTestConfig = {
  testDir: './e2e-tests',
  timeout: 30000,
  expect: {
    timeout: 5000,
  },
  fullyParallel: true,
  forbidOnly: \!\!process.env.CI,
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: [
    ['html'],
    ['junit', { outputFile: 'test-results/junit.xml' }]
  ],
  use: {
    baseURL: process.env.BASE_URL || 'http://localhost:3000',
    trace: 'on-first-retry',
    screenshot: 'only-on-failure',
    video: 'retain-on-failure',
  },
  projects: [
    {
      name: 'chromium',
      use: { ...devices['Desktop Chrome'] },
    },
    {
      name: 'firefox',
      use: { ...devices['Desktop Firefox'] },
    },
    {
      name: 'webkit',
      use: { ...devices['Desktop Safari'] },
    },
    {
      name: 'Mobile Chrome',
      use: { ...devices['Pixel 5'] },
    },
    {
      name: 'Mobile Safari',
      use: { ...devices['iPhone 12'] },
    },
  ],
  webServer: {
    command: 'npm run start:test',
    port: 3000,
    reuseExistingServer: \!process.env.CI,
  },
};

export default config;

// E2E test for patient registration workflow
import { test, expect } from '@playwright/test';

test.describe('Patient Registration Workflow', () => {
  test.beforeEach(async ({ page }) => {
    await page.goto('/login');
    await page.fill('[data-testid=email]', 'therapist@example.com');
    await page.fill('[data-testid=password]', 'password123');
    await page.click('[data-testid=login-button]');
    await expect(page).toHaveURL('/dashboard');
  });

  test('should register new patient successfully', async ({ page }) => {
    // Navigate to patient registration
    await page.click('[data-testid=add-patient-button]');
    await expect(page).toHaveURL('/patients/new');

    // Fill patient information
    await page.fill('[data-testid=first-name]', 'Emily');
    await page.fill('[data-testid=last-name]', 'Johnson');
    await page.fill('[data-testid=date-of-birth]', '2019-03-15');
    await page.selectOption('[data-testid=gender]', 'female');
    
    // Add diagnosis
    await page.click('[data-testid=add-diagnosis]');
    await page.fill('[data-testid=diagnosis-input]', 'Cerebral Palsy');
    await page.click('[data-testid=confirm-diagnosis]');

    // Guardian information
    await page.fill('[data-testid=guardian-name]', 'Sarah Johnson');
    await page.fill('[data-testid=guardian-email]', 'sarah.johnson@email.com');
    await page.fill('[data-testid=guardian-phone]', '+1-555-987-6543');

    // Submit form
    await page.click('[data-testid=submit-patient]');

    // Verify success
    await expect(page.locator('[data-testid=success-message]')).toBeVisible();
    await expect(page).toHaveURL(/\/patients\/[a-f0-9-]+$/);
    
    // Verify patient data is displayed
    await expect(page.locator('[data-testid=patient-name]')).toContainText('Emily Johnson');
    await expect(page.locator('[data-testid=patient-diagnosis]')).toContainText('Cerebral Palsy');
  });

  test('should show validation errors for incomplete form', async ({ page }) => {
    await page.click('[data-testid=add-patient-button]');
    
    // Try to submit empty form
    await page.click('[data-testid=submit-patient]');

    // Check validation errors
    await expect(page.locator('[data-testid=first-name-error]')).toContainText('First name is required');
    await expect(page.locator('[data-testid=last-name-error]')).toContainText('Last name is required');
    await expect(page.locator('[data-testid=dob-error]')).toContainText('Date of birth is required');
  });

  test('should support accessibility navigation', async ({ page }) => {
    await page.click('[data-testid=add-patient-button]');
    
    // Test keyboard navigation
    await page.keyboard.press('Tab');
    await expect(page.locator('[data-testid=first-name]')).toBeFocused();
    
    await page.keyboard.press('Tab');
    await expect(page.locator('[data-testid=last-name]')).toBeFocused();

    // Test screen reader labels
    const firstNameInput = page.locator('[data-testid=first-name]');
    await expect(firstNameInput).toHaveAttribute('aria-label', 'Patient first name');
    
    // Test error announcements
    await page.click('[data-testid=submit-patient]');
    const errorRegion = page.locator('[aria-live=polite]');
    await expect(errorRegion).toContainText('Please correct the errors below');
  });
});

// E2E test for therapy session workflow
test.describe('Therapy Session Management', () => {
  test('should complete full session workflow', async ({ page }) => {
    // Login and navigate to patient
    await loginAsTherapist(page);
    await page.goto('/patients/patient-123');

    // Schedule new session
    await page.click('[data-testid=schedule-session]');
    await page.selectOption('[data-testid=session-type]', 'OT');
    await page.fill('[data-testid=session-date]', '2024-01-20');
    await page.fill('[data-testid=session-time]', '09:00');
    await page.fill('[data-testid=duration]', '60');
    await page.click('[data-testid=save-session]');

    // Verify session appears in calendar
    await expect(page.locator('[data-testid=session-calendar]')).toContainText('OT Session');

    // Start session
    await page.click('[data-testid=start-session]');
    await expect(page.locator('[data-testid=session-timer]')).toBeVisible();

    // Add session notes
    await page.fill('[data-testid=session-summary]', 'Patient worked on fine motor skills');
    await page.click('[data-testid=add-goal]');
    await page.fill('[data-testid=goal-progress]', 'Improved pencil grip by 25%');

    // Complete session
    await page.click('[data-testid=complete-session]');
    await expect(page.locator('[data-testid=session-completed]')).toBeVisible();

    // Verify session data is saved
    await page.reload();
    await expect(page.locator('[data-testid=last-session-notes]')).toContainText('fine motor skills');
  });
});
```

### Performance Testing with Artillery
```yaml
# artillery-config.yml
config:
  target: 'https://api.therapy-platform.com'
  phases:
    - duration: 60
      arrivalRate: 10
      name: "Warm up"
    - duration: 120
      arrivalRate: 50
      name: "Ramp up load"
    - duration: 300
      arrivalRate: 100
      name: "Sustained load"
    - duration: 60
      arrivalRate: 200
      name: "Spike test"
  defaults:
    headers:
      Content-Type: 'application/json'

scenarios:
  - name: "Patient API Load Test"
    weight: 30
    flow:
      - post:
          url: "/auth/login"
          json:
            email: "{{ $randomEmail() }}"
            password: "testPassword123"
          capture:
            - json: "$.token"
              as: "authToken"
      - get:
          url: "/api/patients"
          headers:
            Authorization: "Bearer {{ authToken }}"
          expect:
            - statusCode: 200
            - contentType: json
      - get:
          url: "/api/patients/{{ $randomUuid() }}"
          headers:
            Authorization: "Bearer {{ authToken }}"
          expect:
            - statusCode: [200, 404]

  - name: "Session Management Load Test"
    weight: 40
    flow:
      - post:
          url: "/auth/login"
          json:
            email: "therapist{{ $randomInt(1, 100) }}@test.com"
            password: "testPassword123"
          capture:
            - json: "$.token"
              as: "authToken"
      - post:
          url: "/api/sessions"
          headers:
            Authorization: "Bearer {{ authToken }}"
          json:
            patientId: "{{ $randomUuid() }}"
            sessionType: "{{ $randomChoice(['OT', 'PT', 'SLP']) }}"
            scheduledStart: "{{ $randomISOTimestamp() }}"
            duration: "{{ $randomInt(30, 90) }}"
          expect:
            - statusCode: [201, 400]

  - name: "Resource Search Load Test"
    weight: 20
    flow:
      - get:
          url: "/api/resources/search"
          qs:
            q: "{{ $randomChoice(['autism', 'motor skills', 'speech therapy']) }}"
            type: "{{ $randomChoice(['worksheet', 'activity', 'assessment']) }}"
            page: "{{ $randomInt(1, 5) }}"
          expect:
            - statusCode: 200
            - hasProperty: "resources"

  - name: "File Upload Performance Test"
    weight: 10
    flow:
      - post:
          url: "/auth/login"
          json:
            email: "therapist@test.com"
            password: "testPassword123"
          capture:
            - json: "$.token"
              as: "authToken"
      - post:
          url: "/api/uploads"
          headers:
            Authorization: "Bearer {{ authToken }}"
          formData:
            file: "test-files/sample-assessment.pdf"
            type: "assessment"
          expect:
            - statusCode: 201
            - hasProperty: "uploadId"
```

### Security Testing Framework
```typescript
// Security test suite
import { test, expect } from '@playwright/test';
import { SecurityTester } from './security-utils';

describe('Security Tests', () => {
  let securityTester: SecurityTester;

  beforeEach(() => {
    securityTester = new SecurityTester();
  });

  describe('Authentication Security', () => {
    test('should prevent SQL injection in login', async () => {
      const sqlInjectionPayloads = [
        "' OR '1'='1",
        "'; DROP TABLE users; --",
        "' UNION SELECT * FROM users --"
      ];

      for (const payload of sqlInjectionPayloads) {
        const response = await securityTester.testLogin({
          email: payload,
          password: 'password'
        });

        expect(response.status).not.toBe(200);
        expect(response.body).not.toContain('logged in');
      }
    });

    test('should enforce rate limiting', async () => {
      const results = await securityTester.testRateLimit('/auth/login', {
        requests: 100,
        timeWindow: 60000, // 1 minute
        expectedLimit: 10
      });

      expect(results.blockedRequests).toBeGreaterThan(80);
      expect(results.firstBlockStatusCode).toBe(429);
    });

    test('should validate JWT tokens properly', async () => {
      const invalidTokens = [
        'invalid.jwt.token',
        'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.invalid.signature',
        '', // empty token
        'Bearer malformed-token'
      ];

      for (const token of invalidTokens) {
        const response = await securityTester.testApiAccess('/api/patients', token);
        expect(response.status).toBe(401);
      }
    });
  });

  describe('Data Protection', () => {
    test('should encrypt sensitive patient data', async () => {
      const patientData = {
        firstName: 'John',
        lastName: 'Doe',
        ssn: '123-45-6789',
        medicalHistory: 'Sensitive medical information'
      };

      const response = await securityTester.createPatient(patientData);
      expect(response.status).toBe(201);

      // Verify data is encrypted in database
      const dbData = await securityTester.getPatientFromDB(response.body.id);
      expect(dbData.ssn).not.toBe('123-45-6789');
      expect(dbData.ssn).toMatch(/^[a-f0-9]{64}$/); // Encrypted hash
    });

    test('should prevent unauthorized data access', async () => {
      // Create patient with therapist A
      const patientId = await securityTester.createPatientAsTherapist('therapist-a');
      
      // Try to access with therapist B
      const response = await securityTester.accessPatientAsTherapist(patientId, 'therapist-b');
      expect(response.status).toBe(403);
      expect(response.body.error).toContain('unauthorized');
    });

    test('should audit all data access', async () => {
      const patientId = 'patient-123';
      await securityTester.accessPatient(patientId);

      const auditLogs = await securityTester.getAuditLogs({
        resourceType: 'patient',
        resourceId: patientId,
        timeWindow: 60000
      });

      expect(auditLogs).toHaveLength(1);
      expect(auditLogs[0].action).toBe('read');
      expect(auditLogs[0].resourceId).toBe(patientId);
      expect(auditLogs[0].timestamp).toBeDefined();
    });
  });

  describe('Input Validation', () => {
    test('should sanitize HTML input', async () => {
      const maliciousInputs = [
        '<script>alert("xss")</script>',
        '<img src=x onerror=alert("xss")>',
        'javascript:alert("xss")',
        '<iframe src="javascript:alert(\'xss\')"></iframe>'
      ];

      for (const input of maliciousInputs) {
        const response = await securityTester.createPatient({
          firstName: input,
          lastName: 'Test'
        });

        if (response.status === 201) {
          expect(response.body.firstName).not.toContain('<script>');
          expect(response.body.firstName).not.toContain('javascript:');
        }
      }
    });

    test('should validate file uploads', async () => {
      const maliciousFiles = [
        { name: 'virus.exe', content: 'malicious executable' },
        { name: 'script.js', content: 'alert("xss")' },
        { name: '../../../etc/passwd', content: 'path traversal attempt' }
      ];

      for (const file of maliciousFiles) {
        const response = await securityTester.uploadFile(file);
        expect(response.status).toBe(400);
        expect(response.body.error).toContain('invalid file');
      }
    });
  });

  describe('Session Security', () => {
    test('should expire sessions after inactivity', async () => {
      const token = await securityTester.login();
      
      // Wait for session timeout (simulate with time manipulation)
      await securityTester.advanceTime(30 * 60 * 1000); // 30 minutes

      const response = await securityTester.testApiAccess('/api/patients', token);
      expect(response.status).toBe(401);
      expect(response.body.error).toContain('session expired');
    });

    test('should prevent session fixation', async () => {
      const sessionId1 = await securityTester.getSessionId();
      await securityTester.login();
      const sessionId2 = await securityTester.getSessionId();

      expect(sessionId1).not.toBe(sessionId2);
    });
  });
});
```

### Accessibility Testing
```typescript
// Accessibility test suite using axe-core
import { test, expect } from '@playwright/test';
import AxeBuilder from '@axe-core/playwright';

test.describe('Accessibility Tests', () => {
  test('should pass accessibility audit on main pages', async ({ page }) => {
    const pages = [
      '/login',
      '/dashboard',
      '/patients',
      '/patients/new',
      '/sessions',
      '/resources'
    ];

    for (const pagePath of pages) {
      await page.goto(pagePath);
      
      const accessibilityScanResults = await new AxeBuilder({ page })
        .withTags(['wcag2a', 'wcag2aa', 'wcag21aa'])
        .analyze();

      expect(accessibilityScanResults.violations).toEqual([]);
    }
  });

  test('should support keyboard navigation', async ({ page }) => {
    await page.goto('/patients');

    // Test tab navigation
    await page.keyboard.press('Tab');
    await expect(page.locator('[data-testid=search-input]')).toBeFocused();

    await page.keyboard.press('Tab');
    await expect(page.locator('[data-testid=add-patient-button]')).toBeFocused();

    // Test Enter key activation
    await page.keyboard.press('Enter');
    await expect(page).toHaveURL('/patients/new');
  });

  test('should provide proper ARIA labels', async ({ page }) => {
    await page.goto('/patients/new');

    // Check form labels
    const requiredFields = [
      '[data-testid=first-name]',
      '[data-testid=last-name]',
      '[data-testid=date-of-birth]'
    ];

    for (const field of requiredFields) {
      const element = page.locator(field);
      await expect(element).toHaveAttribute('aria-required', 'true');
      await expect(element).toHaveAttribute('aria-label');
    }
  });

  test('should announce errors to screen readers', async ({ page }) => {
    await page.goto('/patients/new');
    await page.click('[data-testid=submit-patient]');

    // Check for aria-live region with errors
    const errorRegion = page.locator('[aria-live=polite]');
    await expect(errorRegion).toBeVisible();
    await expect(errorRegion).toContainText('Please correct the errors');

    // Check field-specific error messages
    const firstNameError = page.locator('[data-testid=first-name-error]');
    await expect(firstNameError).toHaveAttribute('aria-live', 'polite');
  });
});
```

### Mobile Testing Configuration
```typescript
// Mobile-specific test configuration
const mobileDevices = [
  'iPhone 12',
  'iPhone 12 Pro',
  'iPad Pro',
  'Pixel 5',
  'Galaxy S21',
  'Galaxy Tab S7'
];

test.describe('Mobile Responsiveness Tests', () => {
  for (const deviceName of mobileDevices) {
    test(`should work correctly on ${deviceName}`, async ({ browser }) => {
      const context = await browser.newContext({
        ...devices[deviceName]
      });
      const page = await context.newPage();

      await page.goto('/dashboard');

      // Test touch interactions
      await page.tap('[data-testid=menu-button]');
      await expect(page.locator('[data-testid=mobile-menu]')).toBeVisible();

      // Test responsive layout
      const viewport = page.viewportSize();
      if (viewport.width < 768) {
        // Mobile layout
        await expect(page.locator('[data-testid=sidebar]')).not.toBeVisible();
        await expect(page.locator('[data-testid=mobile-nav]')).toBeVisible();
      } else {
        // Tablet layout
        await expect(page.locator('[data-testid=sidebar]')).toBeVisible();
      }

      await context.close();
    });
  }
});
```

### CI/CD Pipeline Testing Integration
```yaml
# .github/workflows/test.yml
name: Comprehensive Testing Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: therapy_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm run test:unit
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/therapy_test

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Start test environment
      run: docker-compose -f docker-compose.test.yml up -d

    - name: Run integration tests
      run: npm run test:integration

    - name: Stop test environment
      run: docker-compose -f docker-compose.test.yml down

  e2e-tests:
    runs-on: ubuntu-latest
    needs: integration-tests
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright
      run: npx playwright install --with-deps

    - name: Start application
      run: npm run start:test &

    - name: Run E2E tests
      run: npm run test:e2e

    - name: Upload test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: playwright-report
        path: playwright-report/

  security-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Run OWASP ZAP scan
      uses: zaproxy/action-full-scan@v0.4.0
      with:
        target: 'http://localhost:3000'

    - name: Run dependency security audit
      run: npm audit --audit-level high

    - name: Run CodeQL analysis
      uses: github/codeql-action/analyze@v2

  performance-tests:
    runs-on: ubuntu-latest
    needs: integration-tests
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install Artillery
      run: npm install -g artillery

    - name: Start application
      run: npm run start:test &

    - name: Run performance tests
      run: artillery run performance-tests/load-test.yml

    - name: Upload performance results
      uses: actions/upload-artifact@v3
      with:
        name: performance-report
        path: performance-results/
```

### Performance Requirements
- Unit test execution: < 30 seconds
- Integration test suite: < 5 minutes
- E2E test suite: < 15 minutes
- Performance test duration: < 10 minutes
- Security scan completion: < 20 minutes
- Code coverage reporting: < 2 minutes
- Test result processing: < 1 minute

### Quality Gates
- Code coverage: >90% for all components
- Performance regression: <5% increase in response times
- Security scan: Zero high-severity vulnerabilities
- Accessibility: Zero WCAG 2.1 AA violations
- Mobile compatibility: All tests pass on target devices
- Browser compatibility: Support for latest 2 versions
- API response time: <500ms for 95th percentile
