### ISSUE TITLE
INFRA-002: CI/CD Pipeline and GitOps Automation

### ISSUE THREAD

**Issue by sean-rowe** [sean-rowe/pediatric-therapy-resource#57]
## Story
As a DevOps engineer, I want comprehensive CI/CD pipeline automation with GitOps workflows, so that code changes are automatically tested, built, deployed, and monitored across all environments with zero-downtime deployments and automated rollbacks.

## Acceptance Criteria
- Automated CI/CD pipelines for all microservices
- GitOps-based deployment management
- Multi-environment promotion (dev, staging, prod)
- Automated testing integration at all stages
- Container image security scanning
- Infrastructure drift detection and correction
- Automated rollback on deployment failures
- Deployment metrics and observability

### GitHub Actions CI/CD Pipeline
```yaml
name: Therapy Platform CI/CD

on:
  push:
    branches: [ main, develop, 'feature/*', 'hotfix/*' ]
  pull_request:
    branches: [ main, develop ]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Lint code
      run: npm run lint

    - name: Type check
      run: npm run type-check

    - name: Security audit
      run: npm audit --audit-level high

    - name: SonarCloud Scan
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

  unit-tests:
    runs-on: ubuntu-latest
    needs: code-quality
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: therapy_test
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

      redis:
        image: redis:7
        options: >-
          --health-cmd "redis-cli ping"
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 6379:6379

    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Run unit tests
      run: npm run test:unit -- --coverage
      env:
        DATABASE_URL: postgres://postgres:postgres@localhost:5432/therapy_test
        REDIS_URL: redis://localhost:6379

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage/lcov.info
        flags: unit-tests
        name: codecov-umbrella

    - name: Coverage threshold check
      run:  < /dev/null | 
        COVERAGE=$(cat coverage/coverage-summary.json | jq '.total.lines.pct')
        if (( $(echo "$COVERAGE < 90" | bc -l) )); then
          echo "Coverage $COVERAGE% is below 90% threshold"
          exit 1
        fi

  integration-tests:
    runs-on: ubuntu-latest
    needs: unit-tests
    strategy:
      matrix:
        service: [api, worker, scheduler]
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Start test environment
      run: |
        docker-compose -f docker-compose.test.yml up -d
        sleep 30

    - name: Wait for services
      run: |
        timeout 300 bash -c 'until curl -f http://localhost:3000/health; do sleep 5; done'

    - name: Run integration tests
      run: npm run test:integration:${{ matrix.service }}

    - name: Collect service logs
      if: failure()
      run: |
        docker-compose -f docker-compose.test.yml logs > integration-logs-${{ matrix.service }}.txt

    - name: Upload logs
      if: failure()
      uses: actions/upload-artifact@v3
      with:
        name: integration-logs-${{ matrix.service }}
        path: integration-logs-${{ matrix.service }}.txt

    - name: Cleanup
      if: always()
      run: docker-compose -f docker-compose.test.yml down -v

  security-scan:
    runs-on: ubuntu-latest
    needs: code-quality
    steps:
    - uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        scan-ref: '.'
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-results.sarif'

    - name: OWASP Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: 'therapy-platform'
        path: '.'
        format: 'ALL'

    - name: Semgrep Security Scan
      run: |
        python -m pip install semgrep
        semgrep --config=auto --json --output=semgrep-results.json .

    - name: Upload security scan results
      uses: actions/upload-artifact@v3
      with:
        name: security-scan-results
        path: |
          trivy-results.sarif
          reports/
          semgrep-results.json

  build-and-push:
    runs-on: ubuntu-latest
    needs: [unit-tests, integration-tests, security-scan]
    if: github.event_name == 'push'
    strategy:
      matrix:
        service: [api, worker, scheduler, frontend]
    
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
      image-tag: ${{ steps.meta.outputs.tags }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v5
      with:
        context: .
        file: ./services/${{ matrix.service }}/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64

    - name: Scan container image
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/${{ matrix.service }}:${{ github.sha }}
        format: 'sarif'
        output: 'trivy-image-results.sarif'

    - name: Upload image scan results
      uses: github/codeql-action/upload-sarif@v2
      with:
        sarif_file: 'trivy-image-results.sarif'

  deploy-development:
    runs-on: ubuntu-latest
    needs: build-and-push
    if: github.ref == 'refs/heads/develop'
    environment: development
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name therapy-platform-dev --region us-west-2

    - name: Deploy to development
      run: |
        # Update image tags in kustomization
        cd k8s/overlays/development
        kustomize edit set image api=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/api:${{ github.sha }}
        kustomize edit set image worker=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/worker:${{ github.sha }}
        kustomize edit set image scheduler=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/scheduler:${{ github.sha }}
        kustomize edit set image frontend=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:${{ github.sha }}
        
        # Apply changes
        kubectl apply -k .

    - name: Wait for deployment
      run: |
        kubectl rollout status deployment/therapy-api -n therapy-platform --timeout=600s
        kubectl rollout status deployment/therapy-worker -n therapy-platform --timeout=600s
        kubectl rollout status deployment/therapy-scheduler -n therapy-platform --timeout=600s
        kubectl rollout status deployment/therapy-frontend -n therapy-platform --timeout=600s

    - name: Run smoke tests
      run: |
        ENDPOINT=$(kubectl get ingress therapy-api-ingress -n therapy-platform -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
        curl -f https://$ENDPOINT/health || exit 1
        npm run test:smoke -- --endpoint=https://$ENDPOINT

  e2e-tests:
    runs-on: ubuntu-latest
    needs: deploy-development
    if: github.ref == 'refs/heads/develop'
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'

    - name: Install dependencies
      run: npm ci

    - name: Install Playwright
      run: npx playwright install --with-deps

    - name: Run E2E tests
      run: npm run test:e2e
      env:
        BASE_URL: https://dev.therapy-platform.com
        TEST_USER_EMAIL: ${{ secrets.TEST_USER_EMAIL }}
        TEST_USER_PASSWORD: ${{ secrets.TEST_USER_PASSWORD }}

    - name: Upload E2E test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: e2e-test-results
        path: |
          test-results/
          playwright-report/

  performance-tests:
    runs-on: ubuntu-latest
    needs: deploy-development
    if: github.ref == 'refs/heads/develop'
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Install Artillery
      run: npm install -g artillery@latest

    - name: Run performance tests
      run: |
        artillery run performance-tests/load-test.yml \
          --target https://dev.therapy-platform.com \
          --output performance-results.json

    - name: Generate performance report
      run: artillery report performance-results.json --output performance-report.html

    - name: Performance regression check
      run: |
        # Compare with baseline performance metrics
        node scripts/check-performance-regression.js performance-results.json

    - name: Upload performance results
      uses: actions/upload-artifact@v3
      with:
        name: performance-test-results
        path: |
          performance-results.json
          performance-report.html

  deploy-staging:
    runs-on: ubuntu-latest
    needs: [e2e-tests, performance-tests]
    if: github.ref == 'refs/heads/main'
    environment: staging
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-west-2

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name therapy-platform-staging --region us-west-2

    - name: Blue-Green Deployment to Staging
      run: |
        # Create new deployment with blue/green strategy
        cd k8s/overlays/staging
        
        # Update image tags
        kustomize edit set image api=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/api:${{ github.sha }}
        kustomize edit set image worker=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/worker:${{ github.sha }}
        kustomize edit set image scheduler=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/scheduler:${{ github.sha }}
        kustomize edit set image frontend=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:${{ github.sha }}
        
        # Deploy to green environment
        kubectl apply -k . --dry-run=client -o yaml | sed 's/therapy-/therapy-green-/g' | kubectl apply -f -
        
        # Wait for green deployment
        kubectl rollout status deployment/therapy-green-api -n therapy-platform --timeout=600s
        
        # Run health checks on green environment
        GREEN_ENDPOINT=$(kubectl get service therapy-green-api-service -n therapy-platform -o jsonpath='{.status.loadBalancer.ingress[0].hostname}')
        curl -f http://$GREEN_ENDPOINT/health || exit 1
        
        # Switch traffic to green
        kubectl patch service therapy-api-service -n therapy-platform -p '{"spec":{"selector":{"app":"therapy-green-api"}}}'
        
        # Cleanup old blue deployment
        kubectl delete deployment therapy-api -n therapy-platform || true

    - name: Run staging validation tests
      run: |
        npm run test:staging-validation
        npm run test:accessibility
        npm run test:security

  deploy-production:
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.ref == 'refs/heads/main'
    environment: production
    
    steps:
    - uses: actions/checkout@v4

    - name: Setup kubectl
      uses: azure/setup-kubectl@v3
      with:
        version: 'v1.28.0'

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v4
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID_PROD }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY_PROD }}
        aws-region: us-west-2

    - name: Update kubeconfig
      run: aws eks update-kubeconfig --name therapy-platform-prod --region us-west-2

    - name: Canary Deployment to Production
      run: |
        cd k8s/overlays/production
        
        # Update image tags
        kustomize edit set image api=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/api:${{ github.sha }}
        kustomize edit set image worker=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/worker:${{ github.sha }}
        kustomize edit set image scheduler=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/scheduler:${{ github.sha }}
        kustomize edit set image frontend=${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}/frontend:${{ github.sha }}
        
        # Deploy canary (10% traffic)
        kubectl apply -k canary/
        
        # Wait for canary deployment
        kubectl rollout status deployment/therapy-api-canary -n therapy-platform --timeout=600s

    - name: Canary Analysis
      run: |
        # Monitor canary metrics for 10 minutes
        sleep 600
        
        # Check error rates and performance metrics
        ERROR_RATE=$(kubectl exec -n monitoring deployment/prometheus -- \
          promtool query instant 'rate(http_requests_total{status=~"5.."}[5m]) / rate(http_requests_total[5m])' | \
          grep -o '[0-9.]*')
        
        if (( $(echo "$ERROR_RATE > 0.01" | bc -l) )); then
          echo "Canary error rate $ERROR_RATE is too high, rolling back"
          kubectl delete -k canary/
          exit 1
        fi
        
        # Check response time
        AVG_RESPONSE_TIME=$(kubectl exec -n monitoring deployment/prometheus -- \
          promtool query instant 'histogram_quantile(0.95, rate(http_request_duration_seconds_bucket[5m]))' | \
          grep -o '[0-9.]*')
        
        if (( $(echo "$AVG_RESPONSE_TIME > 0.5" | bc -l) )); then
          echo "Canary response time $AVG_RESPONSE_TIME is too high, rolling back"
          kubectl delete -k canary/
          exit 1
        fi

    - name: Full Production Deployment
      run: |
        # Gradually increase traffic to canary
        for traffic in 25 50 75 100; do
          kubectl patch virtualservice therapy-api-vs -n therapy-platform --type='json' \
            -p="[{'op': 'replace', 'path': '/spec/http/0/match/0/weight', 'value': $traffic}]"
          
          sleep 300  # Wait 5 minutes between traffic increases
          
          # Monitor metrics during traffic increase
          ./scripts/check-deployment-health.sh || {
            echo "Health check failed at $traffic% traffic, rolling back"
            kubectl delete -k canary/
            exit 1
          }
        done
        
        # Replace main deployment with canary
        kubectl apply -k .
        kubectl delete -k canary/

    - name: Post-deployment validation
      run: |
        # Run comprehensive production validation
        npm run test:production-validation
        
        # Verify all services are healthy
        kubectl get pods -n therapy-platform
        kubectl get services -n therapy-platform
        
        # Check external endpoints
        curl -f https://api.therapy-platform.com/health
        curl -f https://therapy-platform.com/health

  notify-deployment:
    runs-on: ubuntu-latest
    needs: [deploy-production]
    if: always()
    
    steps:
    - name: Notify Slack on Success
      if: needs.deploy-production.result == 'success'
      uses: 8398a7/action-slack@v3
      with:
        status: success
        text: '🚀 Production deployment successful\!'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}

    - name: Notify Slack on Failure
      if: needs.deploy-production.result == 'failure'
      uses: 8398a7/action-slack@v3
      with:
        status: failure
        text: '🔴 Production deployment failed\!'
        webhook_url: ${{ secrets.SLACK_WEBHOOK }}

    - name: Create deployment record
      run: |
        curl -X POST https://api.therapy-platform.com/internal/deployments \
          -H "Authorization: Bearer ${{ secrets.INTERNAL_API_TOKEN }}" \
          -H "Content-Type: application/json" \
          -d '{
            "sha": "${{ github.sha }}",
            "environment": "production",
            "status": "${{ needs.deploy-production.result }}",
            "deployed_at": "'$(date -u +%Y-%m-%dT%H:%M:%SZ)'",
            "deployed_by": "${{ github.actor }}"
          }'
```

### GitOps Repository Structure
```
gitops-config/
├── applications/
│   ├── api/
│   │   ├── base/
│   │   │   ├── deployment.yaml
│   │   │   ├── service.yaml
│   │   │   ├── configmap.yaml
│   │   │   └── kustomization.yaml
│   │   └── overlays/
│   │       ├── development/
│   │       ├── staging/
│   │       └── production/
│   ├── worker/
│   ├── scheduler/
│   └── frontend/
├── infrastructure/
│   ├── aws/
│   │   ├── eks/
│   │   ├── rds/
│   │   ├── elasticache/
│   │   └── s3/
│   └── monitoring/
│       ├── prometheus/
│       ├── grafana/
│       └── alertmanager/
└── argocd/
    ├── applications/
    ├── projects/
    └── repositories/
```

### ArgoCD Application Manifests
```yaml
# argocd/applications/therapy-platform-api.yaml
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: therapy-platform-api
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: therapy-platform
  source:
    repoURL: https://github.com/org/therapy-platform-gitops
    targetRevision: HEAD
    path: applications/api/overlays/production
  destination:
    server: https://kubernetes.default.svc
    namespace: therapy-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
    - CreateNamespace=true
    - PruneLast=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
  revisionHistoryLimit: 10

---
# ArgoCD AppProject
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: therapy-platform
  namespace: argocd
spec:
  description: Pediatric Therapy Platform Applications
  sourceRepos:
  - https://github.com/org/therapy-platform-gitops
  - https://github.com/org/therapy-platform
  destinations:
  - namespace: therapy-platform
    server: https://kubernetes.default.svc
  - namespace: therapy-platform-staging
    server: https://kubernetes.default.svc
  clusterResourceWhitelist:
  - group: ''
    kind: Namespace
  - group: rbac.authorization.k8s.io
    kind: ClusterRole
  - group: rbac.authorization.k8s.io
    kind: ClusterRoleBinding
  namespaceResourceWhitelist:
  - group: ''
    kind: ConfigMap
  - group: ''
    kind: Secret
  - group: ''
    kind: Service
  - group: apps
    kind: Deployment
  - group: networking.k8s.io
    kind: Ingress
  roles:
  - name: admin
    description: Admin privileges
    policies:
    - p, proj:therapy-platform:admin, applications, *, therapy-platform/*, allow
    - p, proj:therapy-platform:admin, repositories, *, *, allow
    groups:
    - therapy-platform:admins
```

### Helm Charts for Complex Deployments
```yaml
# charts/therapy-platform/Chart.yaml
apiVersion: v2
name: therapy-platform
description: Pediatric Therapy Platform Helm Chart
type: application
version: 0.1.0
appVersion: "1.0.0"

dependencies:
- name: postgresql
  version: 12.1.9
  repository: https://charts.bitnami.com/bitnami
  condition: postgresql.enabled
- name: redis
  version: 17.8.0
  repository: https://charts.bitnami.com/bitnami
  condition: redis.enabled

# charts/therapy-platform/values.yaml
global:
  imageRegistry: ghcr.io
  imagePullSecrets:
    - name: github-registry-secret

api:
  image:
    repository: therapy-platform/api
    tag: "latest"
    pullPolicy: IfNotPresent
  
  replicaCount: 3
  
  service:
    type: ClusterIP
    port: 80
    targetPort: 8080
  
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      cert-manager.io/cluster-issuer: "letsencrypt-prod"
      nginx.ingress.kubernetes.io/rate-limit: "100"
    hosts:
      - host: api.therapy-platform.com
        paths:
          - path: /
            pathType: Prefix
    tls:
      - secretName: api-tls
        hosts:
          - api.therapy-platform.com
  
  resources:
    limits:
      cpu: 1000m
      memory: 1Gi
    requests:
      cpu: 500m
      memory: 512Mi
  
  autoscaling:
    enabled: true
    minReplicas: 3
    maxReplicas: 20
    targetCPUUtilizationPercentage: 70
    targetMemoryUtilizationPercentage: 80
  
  env:
    - name: NODE_ENV
      value: "production"
    - name: DATABASE_URL
      valueFrom:
        secretKeyRef:
          name: database-credentials
          key: url
    - name: REDIS_URL
      valueFrom:
        secretKeyRef:
          name: redis-credentials
          key: url

worker:
  image:
    repository: therapy-platform/worker
    tag: "latest"
  
  replicaCount: 2
  
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  
  autoscaling:
    enabled: true
    minReplicas: 2
    maxReplicas: 10
    targetCPUUtilizationPercentage: 80

scheduler:
  image:
    repository: therapy-platform/scheduler
    tag: "latest"
  
  replicaCount: 1
  
  resources:
    limits:
      cpu: 200m
      memory: 256Mi
    requests:
      cpu: 100m
      memory: 128Mi

postgresql:
  enabled: false  # Using AWS RDS
  
redis:
  enabled: false  # Using AWS ElastiCache

monitoring:
  prometheus:
    enabled: true
  grafana:
    enabled: true
  alertmanager:
    enabled: true
```

### Terraform GitOps Integration
```hcl
# terraform/modules/gitops/main.tf
resource "kubernetes_namespace" "argocd" {
  metadata {
    name = "argocd"
    labels = {
      "app.kubernetes.io/name" = "argocd"
    }
  }
}

resource "helm_release" "argocd" {
  name       = "argocd"
  repository = "https://argoproj.github.io/argo-helm"
  chart      = "argo-cd"
  version    = "5.46.8"
  namespace  = kubernetes_namespace.argocd.metadata[0].name

  values = [
    file("${path.module}/argocd-values.yaml")
  ]

  depends_on = [kubernetes_namespace.argocd]
}

# ArgoCD Configuration
resource "kubernetes_secret" "argocd_repo" {
  metadata {
    name      = "therapy-platform-repo"
    namespace = kubernetes_namespace.argocd.metadata[0].name
    labels = {
      "argocd.argoproj.io/secret-type" = "repository"
    }
  }

  data = {
    type          = "git"
    url           = var.gitops_repo_url
    sshPrivateKey = var.gitops_ssh_key
  }
}

# Bootstrap ArgoCD Application
resource "kubernetes_manifest" "bootstrap_app" {
  manifest = {
    apiVersion = "argoproj.io/v1alpha1"
    kind       = "Application"
    metadata = {
      name      = "bootstrap"
      namespace = kubernetes_namespace.argocd.metadata[0].name
    }
    spec = {
      project = "default"
      source = {
        repoURL        = var.gitops_repo_url
        targetRevision = "HEAD"
        path           = "argocd/applications"
      }
      destination = {
        server    = "https://kubernetes.default.svc"
        namespace = kubernetes_namespace.argocd.metadata[0].name
      }
      syncPolicy = {
        automated = {
          prune    = true
          selfHeal = true
        }
      }
    }
  }

  depends_on = [helm_release.argocd]
}
```

### Deployment Health Monitoring
```bash
#\!/bin/bash
# scripts/check-deployment-health.sh

set -e

NAMESPACE=${1:-therapy-platform}
TIMEOUT=${2:-300}

echo "Checking deployment health in namespace: $NAMESPACE"

# Check pod health
check_pods() {
    echo "Checking pod status..."
    
    READY_PODS=$(kubectl get pods -n $NAMESPACE --field-selector=status.phase=Running -o jsonpath='{.items[*].status.containerStatuses[*].ready}' | tr ' ' '\n' | grep -c true || echo 0)
    TOTAL_PODS=$(kubectl get pods -n $NAMESPACE --field-selector=status.phase=Running -o jsonpath='{.items[*].metadata.name}' | wc -w)
    
    if [ "$READY_PODS" -eq "$TOTAL_PODS" ] && [ "$TOTAL_PODS" -gt 0 ]; then
        echo "✓ All $TOTAL_PODS pods are ready"
        return 0
    else
        echo "✗ Only $READY_PODS/$TOTAL_PODS pods are ready"
        kubectl get pods -n $NAMESPACE
        return 1
    fi
}

# Check service endpoints
check_endpoints() {
    echo "Checking service endpoints..."
    
    for service in $(kubectl get services -n $NAMESPACE -o jsonpath='{.items[*].metadata.name}'); do
        ENDPOINTS=$(kubectl get endpoints $service -n $NAMESPACE -o jsonpath='{.subsets[*].addresses[*].ip}' | wc -w)
        
        if [ "$ENDPOINTS" -gt 0 ]; then
            echo "✓ Service $service has $ENDPOINTS endpoints"
        else
            echo "✗ Service $service has no endpoints"
            return 1
        fi
    done
}

# Check application health endpoints
check_health_endpoints() {
    echo "Checking application health endpoints..."
    
    API_ENDPOINT=$(kubectl get ingress therapy-api-ingress -n $NAMESPACE -o jsonpath='{.status.loadBalancer.ingress[0].hostname}' 2>/dev/null || echo "")
    
    if [ -n "$API_ENDPOINT" ]; then
        HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" https://$API_ENDPOINT/health || echo "000")
        
        if [ "$HTTP_STATUS" = "200" ]; then
            echo "✓ API health endpoint responding"
        else
            echo "✗ API health endpoint returned status $HTTP_STATUS"
            return 1
        fi
    else
        echo "\! No API endpoint found, skipping health check"
    fi
}

# Check resource utilization
check_resource_utilization() {
    echo "Checking resource utilization..."
    
    # Check CPU usage
    CPU_USAGE=$(kubectl top pods -n $NAMESPACE --no-headers | awk '{sum+=$2} END {print sum}' 2>/dev/null || echo "0")
    
    # Check memory usage
    MEMORY_USAGE=$(kubectl top pods -n $NAMESPACE --no-headers | awk '{sum+=$3} END {print sum}' 2>/dev/null || echo "0")
    
    echo "Total CPU usage: ${CPU_USAGE}m"
    echo "Total Memory usage: ${MEMORY_USAGE}Mi"
}

# Check deployment rollout status
check_rollout_status() {
    echo "Checking deployment rollout status..."
    
    for deployment in $(kubectl get deployments -n $NAMESPACE -o jsonpath='{.items[*].metadata.name}'); do
        if \! kubectl rollout status deployment/$deployment -n $NAMESPACE --timeout=${TIMEOUT}s; then
            echo "✗ Deployment $deployment rollout failed"
            return 1
        fi
        echo "✓ Deployment $deployment rollout successful"
    done
}

# Main health check sequence
main() {
    echo "Starting deployment health check..."
    
    check_rollout_status
    check_pods
    check_endpoints
    check_health_endpoints
    check_resource_utilization
    
    echo "✓ All health checks passed\!"
}

# Error handling
trap 'echo "Health check failed with exit code $?"; exit 1' ERR

main "$@"
```

### Performance Requirements
- Pipeline execution time: < 20 minutes for full deployment
- Container build time: < 5 minutes per service
- Test execution: < 10 minutes total
- Security scanning: < 3 minutes
- Deployment rollout: < 5 minutes per environment
- Rollback time: < 2 minutes
- Health check validation: < 30 seconds

### Security Requirements
- Container image vulnerability scanning
- Secrets management with rotation
- Infrastructure drift detection
- Deployment approval workflows for production
- Audit logging for all deployments
- Role-based access control for CI/CD
- Signed container images
- Supply chain security validation
