### ISSUE TITLE
INFRA-003: Monitoring and Observability Platform

### ISSUE THREAD

**Issue by sean-rowe** [sean-rowe/pediatric-therapy-resource#58]
## Story
As a platform operator, I want comprehensive monitoring, observability, and alerting systems, so that I can proactively detect issues, troubleshoot problems quickly, and ensure optimal system performance and availability.

## Acceptance Criteria
- Real-time metrics collection and visualization
- Distributed tracing for request flows
- Centralized logging with search and analysis
- Proactive alerting with intelligent escalation
- Performance monitoring and SLA tracking
- Security monitoring and threat detection
- Cost monitoring and optimization alerts
- Custom dashboards for different stakeholders

### Prometheus Monitoring Stack
```yaml
# monitoring/prometheus/prometheus-config.yaml
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'therapy-platform-prod'
    environment: 'production'

rule_files:
  - "/etc/prometheus/rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Kubernetes API Server
  - job_name: 'kubernetes-apiservers'
    kubernetes_sd_configs:
    - role: endpoints
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - source_labels: [__meta_kubernetes_namespace, __meta_kubernetes_service_name, __meta_kubernetes_endpoint_port_name]
      action: keep
      regex: default;kubernetes;https

  # Kubernetes Nodes
  - job_name: 'kubernetes-nodes'
    kubernetes_sd_configs:
    - role: node
    scheme: https
    tls_config:
      ca_file: /var/run/secrets/kubernetes.io/serviceaccount/ca.crt
    bearer_token_file: /var/run/secrets/kubernetes.io/serviceaccount/token
    relabel_configs:
    - action: labelmap
      regex: __meta_kubernetes_node_label_(.+)

  # Kubernetes Pods
  - job_name: 'kubernetes-pods'
    kubernetes_sd_configs:
    - role: pod
    relabel_configs:
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_scrape]
      action: keep
      regex: true
    - source_labels: [__meta_kubernetes_pod_annotation_prometheus_io_path]
      action: replace
      target_label: __metrics_path__
      regex: (.+)
    - source_labels: [__address__, __meta_kubernetes_pod_annotation_prometheus_io_port]
      action: replace
      regex: ([^:]+)(?::\d+)?;(\d+)
      replacement: $1:$2
      target_label: __address__

  # Application Services
  - job_name: 'therapy-platform-api'
    static_configs:
    - targets: ['therapy-api-service:8080']
    metrics_path: /metrics
    scrape_interval: 30s
    relabel_configs:
    - source_labels: [__address__]
      target_label: service
      replacement: 'therapy-api'

  - job_name: 'therapy-platform-worker'
    static_configs:
    - targets: ['therapy-worker-service:8080']
    metrics_path: /metrics
    scrape_interval: 30s

  # Database Monitoring
  - job_name: 'postgres-exporter'
    static_configs:
    - targets: ['postgres-exporter:9187']
    scrape_interval: 30s

  - job_name: 'redis-exporter'
    static_configs:
    - targets: ['redis-exporter:9121']
    scrape_interval: 30s

  # Infrastructure Monitoring
  - job_name: 'node-exporter'
    kubernetes_sd_configs:
    - role: node
    relabel_configs:
    - source_labels: [__address__]
      regex: '(.*):10250'
      replacement: '${1}:9100'
      target_label: __address__

  # AWS CloudWatch Metrics
  - job_name: 'cloudwatch-exporter'
    static_configs:
    - targets: ['cloudwatch-exporter:9106']
    scrape_interval: 300s  # 5 minutes for AWS metrics

# Alerting Rules
# monitoring/prometheus/rules/therapy-platform-alerts.yml
groups:
- name: therapy-platform.rules
  rules:
  # API Performance Alerts
  - alert: HighAPILatency
    expr: histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{service="therapy-api"}[5m])) > 0.5
    for: 2m
    labels:
      severity: warning
      service: therapy-api
    annotations:
      summary: "High API latency detected"
      description: "API 95th percentile latency is {{ $value }}s for the last 5 minutes"

  - alert: HighAPIErrorRate
    expr: rate(http_requests_total{service="therapy-api",status=~"5.."}[5m]) / rate(http_requests_total{service="therapy-api"}[5m]) > 0.05
    for: 2m
    labels:
      severity: critical
      service: therapy-api
    annotations:
      summary: "High API error rate"
      description: "API error rate is {{ $value  < /dev/null |  humanizePercentage }} over the last 5 minutes"

  # Database Alerts
  - alert: DatabaseConnectionsHigh
    expr: pg_stat_database_numbackends / pg_settings_max_connections * 100 > 80
    for: 5m
    labels:
      severity: warning
      service: postgresql
    annotations:
      summary: "PostgreSQL connection usage high"
      description: "PostgreSQL connection usage is {{ $value }}% of maximum"

  - alert: DatabaseSlowQueries
    expr: pg_stat_statements_mean_time_ms > 1000
    for: 5m
    labels:
      severity: warning
      service: postgresql
    annotations:
      summary: "Slow database queries detected"
      description: "Average query time is {{ $value }}ms"

  # Memory and CPU Alerts
  - alert: PodMemoryUsageHigh
    expr: container_memory_usage_bytes{container\!=""} / container_spec_memory_limit_bytes > 0.9
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Pod memory usage high"
      description: "Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} is using {{ $value | humanizePercentage }} of its memory limit"

  - alert: PodCPUUsageHigh
    expr: rate(container_cpu_usage_seconds_total{container\!=""}[5m]) / container_spec_cpu_quota * container_spec_cpu_period > 0.8
    for: 10m
    labels:
      severity: warning
    annotations:
      summary: "Pod CPU usage high"
      description: "Pod {{ $labels.pod }} CPU usage is {{ $value | humanizePercentage }} of limit"

  # Storage Alerts
  - alert: PersistentVolumeUsageHigh
    expr: kubelet_volume_stats_used_bytes / kubelet_volume_stats_capacity_bytes > 0.85
    for: 5m
    labels:
      severity: warning
    annotations:
      summary: "Persistent volume usage high"
      description: "Volume {{ $labels.persistentvolumeclaim }} is {{ $value | humanizePercentage }} full"

  # Application-Specific Alerts
  - alert: TherapySessionFailureRate
    expr: rate(therapy_session_failures_total[5m]) / rate(therapy_session_attempts_total[5m]) > 0.1
    for: 2m
    labels:
      severity: critical
      service: therapy-platform
    annotations:
      summary: "High therapy session failure rate"
      description: "Therapy session failure rate is {{ $value | humanizePercentage }}"

  - alert: PatientDataSyncFailures
    expr: increase(patient_data_sync_failures_total[10m]) > 5
    for: 0m
    labels:
      severity: critical
      service: therapy-platform
    annotations:
      summary: "Patient data sync failures"
      description: "{{ $value }} patient data sync failures in the last 10 minutes"

  # Security Alerts
  - alert: UnauthorizedAPIAccess
    expr: increase(http_requests_total{status="401"}[5m]) > 100
    for: 0m
    labels:
      severity: warning
      service: security
    annotations:
      summary: "High number of unauthorized API requests"
      description: "{{ $value }} unauthorized requests in the last 5 minutes"

  - alert: SecurityViolationDetected
    expr: increase(security_violations_total[1m]) > 0
    for: 0m
    labels:
      severity: critical
      service: security
    annotations:
      summary: "Security violation detected"
      description: "{{ $value }} security violations detected"

  # Business Metrics Alerts
  - alert: LowTherapySessionBookings
    expr: rate(therapy_sessions_booked_total[1h]) < 10
    for: 30m
    labels:
      severity: warning
      service: business
    annotations:
      summary: "Low therapy session booking rate"
      description: "Only {{ $value }} sessions booked per hour in the last hour"

  - alert: HighPatientChurnRate
    expr: rate(patient_churned_total[24h]) / rate(patient_registered_total[24h]) > 0.1
    for: 1h
    labels:
      severity: warning
      service: business
    annotations:
      summary: "High patient churn rate"
      description: "Patient churn rate is {{ $value | humanizePercentage }} over 24 hours"
```

### Grafana Dashboards
```json
{
  "dashboard": {
    "id": null,
    "title": "Therapy Platform - API Performance",
    "tags": ["therapy-platform", "api", "performance"],
    "timezone": "browser",
    "panels": [
      {
        "id": 1,
        "title": "Request Rate",
        "type": "stat",
        "targets": [
          {
            "expr": "sum(rate(http_requests_total{service=\"therapy-api\"}[5m]))",
            "refId": "A"
          }
        ],
        "fieldConfig": {
          "defaults": {
            "unit": "reqps",
            "min": 0,
            "thresholds": {
              "steps": [
                {"color": "green", "value": null},
                {"color": "yellow", "value": 100},
                {"color": "red", "value": 500}
              ]
            }
          }
        },
        "gridPos": {"h": 8, "w": 6, "x": 0, "y": 0}
      },
      {
        "id": 2,
        "title": "Response Time (95th percentile)",
        "type": "stat",
        "targets": [
          {
            "expr": "histogram_quantile(0.95, rate(http_request_duration_seconds_bucket{service=\"therapy-api\"}[5m]))",
            "refId": "A"
          }
        ],
        "fieldConfig": {
          "defaults": {
            "unit": "s",
            "min": 0,
            "thresholds": {
              "steps": [
                {"color": "green", "value": null},
                {"color": "yellow", "value": 0.5},
                {"color": "red", "value": 1.0}
              ]
            }
          }
        },
        "gridPos": {"h": 8, "w": 6, "x": 6, "y": 0}
      },
      {
        "id": 3,
        "title": "Error Rate",
        "type": "stat",
        "targets": [
          {
            "expr": "sum(rate(http_requests_total{service=\"therapy-api\",status=~\"5..\"}[5m])) / sum(rate(http_requests_total{service=\"therapy-api\"}[5m]))",
            "refId": "A"
          }
        ],
        "fieldConfig": {
          "defaults": {
            "unit": "percentunit",
            "min": 0,
            "max": 1,
            "thresholds": {
              "steps": [
                {"color": "green", "value": null},
                {"color": "yellow", "value": 0.01},
                {"color": "red", "value": 0.05}
              ]
            }
          }
        },
        "gridPos": {"h": 8, "w": 6, "x": 12, "y": 0}
      },
      {
        "id": 4,
        "title": "Active Users",
        "type": "stat",
        "targets": [
          {
            "expr": "therapy_active_users_total",
            "refId": "A"
          }
        ],
        "fieldConfig": {
          "defaults": {
            "unit": "short",
            "min": 0
          }
        },
        "gridPos": {"h": 8, "w": 6, "x": 18, "y": 0}
      },
      {
        "id": 5,
        "title": "Request Rate by Endpoint",
        "type": "graph",
        "targets": [
          {
            "expr": "sum by (endpoint) (rate(http_requests_total{service=\"therapy-api\"}[5m]))",
            "refId": "A",
            "legendFormat": "{{ endpoint }}"
          }
        ],
        "xAxis": {"show": true},
        "yAxes": [
          {
            "label": "Requests/sec",
            "min": 0,
            "show": true
          }
        ],
        "gridPos": {"h": 8, "w": 12, "x": 0, "y": 8}
      },
      {
        "id": 6,
        "title": "Response Time Distribution",
        "type": "heatmap",
        "targets": [
          {
            "expr": "sum(rate(http_request_duration_seconds_bucket{service=\"therapy-api\"}[5m])) by (le)",
            "refId": "A"
          }
        ],
        "gridPos": {"h": 8, "w": 12, "x": 12, "y": 8}
      }
    ],
    "time": {"from": "now-1h", "to": "now"},
    "refresh": "30s"
  }
}
```

### Distributed Tracing with Jaeger
```typescript
// tracing/tracer.ts
import { NodeSDK } from '@opentelemetry/auto-instrumentations-node';
import { JaegerExporter } from '@opentelemetry/exporter-jaeger';
import { Resource } from '@opentelemetry/resources';
import { SemanticResourceAttributes } from '@opentelemetry/semantic-conventions';

const jaegerExporter = new JaegerExporter({
  endpoint: process.env.JAEGER_ENDPOINT || 'http://jaeger-collector:14268/api/traces',
});

const sdk = new NodeSDK({
  resource: new Resource({
    [SemanticResourceAttributes.SERVICE_NAME]: 'therapy-platform-api',
    [SemanticResourceAttributes.SERVICE_VERSION]: process.env.SERVICE_VERSION || '1.0.0',
    [SemanticResourceAttributes.DEPLOYMENT_ENVIRONMENT]: process.env.ENVIRONMENT || 'development',
  }),
  traceExporter: jaegerExporter,
  instrumentations: [], // Auto-instrumentations will be added
});

sdk.start();

// Custom tracing for business operations
import { trace, SpanStatusCode } from '@opentelemetry/api';

export class TherapySessionTracer {
  private tracer = trace.getTracer('therapy-session-service');

  async traceSessionCreation(sessionData: any): Promise<any> {
    const span = this.tracer.startSpan('create_therapy_session');
    
    try {
      span.setAttributes({
        'session.type': sessionData.sessionType,
        'session.duration': sessionData.duration,
        'patient.id': sessionData.patientId,
        'therapist.id': sessionData.therapistId,
      });

      // Business logic here
      const result = await this.createSession(sessionData);

      span.setAttributes({
        'session.id': result.id,
        'session.status': result.status,
      });

      span.setStatus({ code: SpanStatusCode.OK });
      return result;
    } catch (error) {
      span.recordException(error);
      span.setStatus({
        code: SpanStatusCode.ERROR,
        message: error.message,
      });
      throw error;
    } finally {
      span.end();
    }
  }

  async tracePatientDataAccess(patientId: string, accessType: string): Promise<any> {
    const span = this.tracer.startSpan('patient_data_access');
    
    span.setAttributes({
      'patient.id': patientId,
      'access.type': accessType,
      'access.timestamp': new Date().toISOString(),
    });

    try {
      // Add security context
      const userId = this.getCurrentUserId();
      span.setAttributes({
        'user.id': userId,
        'user.role': this.getUserRole(userId),
      });

      const result = await this.accessPatientData(patientId, accessType);
      
      span.setStatus({ code: SpanStatusCode.OK });
      return result;
    } catch (error) {
      span.recordException(error);
      span.setStatus({
        code: SpanStatusCode.ERROR,
        message: error.message,
      });
      throw error;
    } finally {
      span.end();
    }
  }
}

// Database tracing
export class DatabaseTracer {
  private tracer = trace.getTracer('database-service');

  async traceQuery(query: string, params: any[]): Promise<any> {
    const span = this.tracer.startSpan('database_query');
    
    span.setAttributes({
      'db.operation': this.extractOperation(query),
      'db.statement': query,
      'db.connection_string': this.sanitizeConnectionString(),
    });

    const startTime = Date.now();
    
    try {
      const result = await this.executeQuery(query, params);
      
      span.setAttributes({
        'db.rows_affected': result.rowCount || 0,
        'db.duration_ms': Date.now() - startTime,
      });

      span.setStatus({ code: SpanStatusCode.OK });
      return result;
    } catch (error) {
      span.recordException(error);
      span.setStatus({
        code: SpanStatusCode.ERROR,
        message: error.message,
      });
      throw error;
    } finally {
      span.end();
    }
  }
}
```

### Centralized Logging with ELK Stack
```yaml
# logging/elasticsearch/elasticsearch.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: elasticsearch
  namespace: logging
spec:
  serviceName: elasticsearch
  replicas: 3
  selector:
    matchLabels:
      app: elasticsearch
  template:
    metadata:
      labels:
        app: elasticsearch
    spec:
      containers:
      - name: elasticsearch
        image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
        ports:
        - containerPort: 9200
          name: rest
        - containerPort: 9300
          name: inter-node
        env:
        - name: cluster.name
          value: therapy-platform-logs
        - name: node.name
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: discovery.seed_hosts
          value: "elasticsearch-0.elasticsearch,elasticsearch-1.elasticsearch,elasticsearch-2.elasticsearch"
        - name: cluster.initial_master_nodes
          value: "elasticsearch-0,elasticsearch-1,elasticsearch-2"
        - name: ES_JAVA_OPTS
          value: "-Xms2g -Xmx2g"
        - name: xpack.security.enabled
          value: "false"
        resources:
          limits:
            memory: 4Gi
            cpu: 2000m
          requests:
            memory: 2Gi
            cpu: 1000m
        volumeMounts:
        - name: data
          mountPath: /usr/share/elasticsearch/data
  volumeClaimTemplates:
  - metadata:
      name: data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      storageClassName: "gp3"
      resources:
        requests:
          storage: 100Gi

---
# Logstash configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: logstash-config
  namespace: logging
data:
  logstash.yml: |
    http.host: "0.0.0.0"
    xpack.monitoring.elasticsearch.hosts: [ "http://elasticsearch:9200" ]
  
  logstash.conf: |
    input {
      beats {
        port => 5044
      }
    }
    
    filter {
      if [fields][service] == "therapy-api" {
        grok {
          match => { "message" => "%{TIMESTAMP_ISO8601:timestamp} %{LOGLEVEL:level} \[%{DATA:thread}\] %{DATA:logger} - %{GREEDYDATA:log_message}" }
        }
        
        if [log_message] =~ /patient_id/ {
          grok {
            match => { "log_message" => ".*patient_id=(?<patient_id>[^,\s]+)" }
          }
          mutate {
            add_field => { "[@metadata][contains_pii]" => "true" }
          }
        }
        
        # Parse JSON structured logs
        if [log_message] =~ /^\{.*\}$/ {
          json {
            source => "log_message"
          }
        }
      }
      
      # Security event processing
      if [fields][service] == "security" {
        mutate {
          add_field => { "[@metadata][security_event]" => "true" }
          add_tag => [ "security" ]
        }
      }
      
      # Performance metrics extraction
      if [log_message] =~ /response_time/ {
        grok {
          match => { "log_message" => ".*response_time=(?<response_time_ms>\d+)" }
        }
        mutate {
          convert => { "response_time_ms" => "integer" }
        }
      }
      
      # Error log enrichment
      if [level] == "ERROR" {
        mutate {
          add_tag => [ "error" ]
          add_field => { "alert_required" => "true" }
        }
      }
    }
    
    output {
      elasticsearch {
        hosts => ["http://elasticsearch:9200"]
        index => "therapy-platform-%{+YYYY.MM.dd}"
        
        # Route security events to separate index
        if [@metadata][security_event] {
          index => "security-events-%{+YYYY.MM.dd}"
        }
      }
      
      # Send critical errors to alerting system
      if [level] == "ERROR" and [fields][service] {
        http {
          url => "http://alertmanager:9093/api/v1/alerts"
          http_method => "post"
          content_type => "application/json"
          format => "json"
          mapping => {
            "alerts" => [
              {
                "labels" => {
                  "alertname" => "ApplicationError"
                  "service" => "%{[fields][service]}"
                  "severity" => "warning"
                }
                "annotations" => {
                  "summary" => "Application error detected"
                  "description" => "%{log_message}"
                }
              }
            ]
          }
        }
      }
    }

---
# Filebeat DaemonSet for log collection
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: filebeat
  namespace: logging
spec:
  selector:
    matchLabels:
      app: filebeat
  template:
    metadata:
      labels:
        app: filebeat
    spec:
      serviceAccountName: filebeat
      terminationGracePeriodSeconds: 30
      containers:
      - name: filebeat
        image: docker.elastic.co/beats/filebeat:8.11.0
        args: [
          "-c", "/etc/filebeat.yml",
          "-e",
        ]
        env:
        - name: ELASTICSEARCH_HOST
          value: elasticsearch
        - name: ELASTICSEARCH_PORT
          value: "9200"
        - name: LOGSTASH_HOST
          value: logstash
        - name: LOGSTASH_PORT
          value: "5044"
        securityContext:
          runAsUser: 0
        resources:
          limits:
            memory: 200Mi
            cpu: 100m
          requests:
            memory: 100Mi
            cpu: 50m
        volumeMounts:
        - name: config
          mountPath: /etc/filebeat.yml
          readOnly: true
          subPath: filebeat.yml
        - name: data
          mountPath: /usr/share/filebeat/data
        - name: varlibdockercontainers
          mountPath: /var/lib/docker/containers
          readOnly: true
        - name: varlog
          mountPath: /var/log
          readOnly: true
      volumes:
      - name: config
        configMap:
          defaultMode: 0600
          name: filebeat-config
      - name: varlibdockercontainers
        hostPath:
          path: /var/lib/docker/containers
      - name: varlog
        hostPath:
          path: /var/log
      - name: data
        hostPath:
          path: /var/lib/filebeat-data
          type: DirectoryOrCreate
```

### AlertManager Configuration
```yaml
# monitoring/alertmanager/alertmanager.yml
global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alerts@therapy-platform.com'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'web.hook'
  routes:
  - match:
      severity: critical
    receiver: 'critical-alerts'
    group_wait: 0s
    repeat_interval: 5m
  - match:
      service: security
    receiver: 'security-team'
    group_wait: 0s
  - match:
      service: therapy-platform
    receiver: 'platform-team'
  - match:
      service: business
    receiver: 'business-team'

receivers:
- name: 'web.hook'
  webhook_configs:
  - url: 'http://alertmanager-webhook:5001/'

- name: 'critical-alerts'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/...'
    channel: '#critical-alerts'
    title: 'Critical Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
    text: '{{ range .Alerts }}{{ .Annotations.description }}{{ end }}'
    send_resolved: true
  pagerduty_configs:
  - routing_key: 'YOUR_PAGERDUTY_INTEGRATION_KEY'
    description: '{{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'

- name: 'security-team'
  email_configs:
  - to: 'security@therapy-platform.com'
    subject: 'Security Alert: {{ range .Alerts }}{{ .Annotations.summary }}{{ end }}'
    body: |
      {{ range .Alerts }}
      Alert: {{ .Annotations.summary }}
      Description: {{ .Annotations.description }}
      Service: {{ .Labels.service }}
      Severity: {{ .Labels.severity }}
      {{ end }}
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/...'
    channel: '#security-alerts'

- name: 'platform-team'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/...'
    channel: '#platform-alerts'
    title: 'Platform Alert'
    send_resolved: true

- name: 'business-team'
  slack_configs:
  - api_url: 'https://hooks.slack.com/services/...'
    channel: '#business-metrics'
    title: 'Business Metrics Alert'

inhibit_rules:
- source_match:
    severity: 'critical'
  target_match:
    severity: 'warning'
  equal: ['alertname', 'cluster', 'service']
```

### Custom Metrics Collection
```typescript
// metrics/custom-metrics.ts
import { register, Counter, Histogram, Gauge } from 'prom-client';

export class TherapyPlatformMetrics {
  // Business Metrics
  private sessionsBooked = new Counter({
    name: 'therapy_sessions_booked_total',
    help: 'Total number of therapy sessions booked',
    labelNames: ['session_type', 'therapist_specialty'],
  });

  private sessionDuration = new Histogram({
    name: 'therapy_session_duration_minutes',
    help: 'Duration of therapy sessions in minutes',
    labelNames: ['session_type'],
    buckets: [15, 30, 45, 60, 90, 120],
  });

  private activeUsers = new Gauge({
    name: 'therapy_active_users_total',
    help: 'Number of currently active users',
    labelNames: ['user_type'],
  });

  private patientEngagement = new Histogram({
    name: 'patient_engagement_score',
    help: 'Patient engagement scores',
    labelNames: ['age_group', 'diagnosis'],
    buckets: [1, 2, 3, 4, 5],
  });

  // Technical Metrics
  private databaseQueries = new Counter({
    name: 'database_queries_total',
    help: 'Total database queries executed',
    labelNames: ['operation', 'table', 'status'],
  });

  private cacheHits = new Counter({
    name: 'cache_hits_total',
    help: 'Total cache hits',
    labelNames: ['cache_type', 'status'],
  });

  private fileUploads = new Counter({
    name: 'file_uploads_total',
    help: 'Total file uploads',
    labelNames: ['file_type', 'status'],
  });

  // Security Metrics
  private authenticationAttempts = new Counter({
    name: 'authentication_attempts_total',
    help: 'Total authentication attempts',
    labelNames: ['method', 'status'],
  });

  private securityViolations = new Counter({
    name: 'security_violations_total',
    help: 'Total security violations detected',
    labelNames: ['violation_type', 'severity'],
  });

  // Data Quality Metrics
  private dataValidationErrors = new Counter({
    name: 'data_validation_errors_total',
    help: 'Total data validation errors',
    labelNames: ['field', 'error_type'],
  });

  private patientDataSyncFailures = new Counter({
    name: 'patient_data_sync_failures_total',
    help: 'Total patient data sync failures',
    labelNames: ['sync_type', 'error_type'],
  });

  // Methods to update metrics
  recordSessionBooked(sessionType: string, therapistSpecialty: string): void {
    this.sessionsBooked.inc({ session_type: sessionType, therapist_specialty: therapistSpecialty });
  }

  recordSessionDuration(sessionType: string, durationMinutes: number): void {
    this.sessionDuration.observe({ session_type: sessionType }, durationMinutes);
  }

  updateActiveUsers(userType: string, count: number): void {
    this.activeUsers.set({ user_type: userType }, count);
  }

  recordPatientEngagement(ageGroup: string, diagnosis: string, score: number): void {
    this.patientEngagement.observe({ age_group: ageGroup, diagnosis }, score);
  }

  recordDatabaseQuery(operation: string, table: string, status: string): void {
    this.databaseQueries.inc({ operation, table, status });
  }

  recordCacheOperation(cacheType: string, status: string): void {
    this.cacheHits.inc({ cache_type: cacheType, status });
  }

  recordFileUpload(fileType: string, status: string): void {
    this.fileUploads.inc({ file_type: fileType, status });
  }

  recordAuthenticationAttempt(method: string, status: string): void {
    this.authenticationAttempts.inc({ method, status });
  }

  recordSecurityViolation(violationType: string, severity: string): void {
    this.securityViolations.inc({ violation_type: violationType, severity });
  }

  recordDataValidationError(field: string, errorType: string): void {
    this.dataValidationErrors.inc({ field, error_type: errorType });
  }

  recordPatientDataSyncFailure(syncType: string, errorType: string): void {
    this.patientDataSyncFailures.inc({ sync_type: syncType, error_type: errorType });
  }

  // Export metrics for Prometheus
  getMetrics(): string {
    return register.metrics();
  }
}

// Middleware for automatic HTTP metrics collection
export function metricsMiddleware(metrics: TherapyPlatformMetrics) {
  const httpRequestDuration = new Histogram({
    name: 'http_request_duration_seconds',
    help: 'Duration of HTTP requests in seconds',
    labelNames: ['method', 'route', 'status'],
    buckets: [0.1, 0.5, 1, 2, 5],
  });

  const httpRequestsTotal = new Counter({
    name: 'http_requests_total',
    help: 'Total number of HTTP requests',
    labelNames: ['method', 'route', 'status'],
  });

  return (req: any, res: any, next: any) => {
    const startTime = Date.now();

    res.on('finish', () => {
      const duration = (Date.now() - startTime) / 1000;
      const route = req.route?.path || req.path;
      const method = req.method;
      const status = res.statusCode.toString();

      httpRequestDuration.observe({ method, route, status }, duration);
      httpRequestsTotal.inc({ method, route, status });
    });

    next();
  };
}
```

### Performance Requirements
- Metrics collection latency: < 100ms
- Log ingestion rate: 10,000 logs/second
- Dashboard load time: < 3 seconds
- Alert delivery time: < 30 seconds
- Trace data retention: 7 days
- Metrics data retention: 30 days
- Log data retention: 90 days

### Security Requirements
- Encrypted data transmission for all monitoring data
- Role-based access to monitoring dashboards
- Audit logging for monitoring system access
- PII data masking in logs
- Secure storage of monitoring credentials
- Regular security scanning of monitoring components
- Compliance with data retention policies
